import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { Activity, ArrowRight, BadgeCheck, BellRing, Bot, CalendarClock, CheckCircle2, Download, Flame, IndianRupee, Mail, RefreshCw, Search, Target, Trophy, UserPlus, Users, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { GlassCard, Kpi, CrmSkeleton, EmptyState } from "@/components/crm/CrmUI";
import { toast } from "@/hooks/use-toast";
import { fetchLeads, fetchTeam, fetchFollowUps, exportCsv, exportExcel, exportPdf, logActivity, updateLead, stageLabel, CRM_STAGES, type CrmLead, type TeamMember, type FollowUp } from "@/lib/crm";
import CrmAttendancePanel from "@/pages/admin/crm/CrmAttendancePanel";

export default function CrmDashboardPro() {
  const [leads, setLeads] = useState<CrmLead[]>([]);
  const [team, setTeam] = useState<TeamMember[]>([]);
  const [followups, setFollowups] = useState<FollowUp[]>([]);
  const [loading, setLoading] = useState(true);
  const [range, setRange] = useState<"7d"|"30d"|"90d">("30d");
  const [query, setQuery] = useState("");
  const [confirmLead, setConfirmLead] = useState<CrmLead | null>(null);
  const [confirmAction, setConfirmAction] = useState<"accept"|"reject"|null>(null);
  const [actionBusy, setActionBusy] = useState(false);

  const load = async () => { setLoading(true); try { const [l,t,f] = await Promise.all([fetchLeads(),fetchTeam(),fetchFollowUps()]); setLeads(l);setTeam(t);setFollowups(f); } catch(e:any){ toast({title:"CRM data could not load",description:e.message,variant:"destructive"}); } finally { setLoading(false); } };
  useEffect(()=>{load()},[]);

  const stats = useMemo(()=>{ const count=(s:string)=>leads.filter(l=>l.status===s).length; const won=count("won"); const lost=count("lost"); const pipeline=leads.filter(l=>!['won','lost'].includes(l.status)).reduce((n,l)=>n+(Number(l.deal_value)||0),0); const overdue=followups.filter(f=>!f.completed&&new Date(f.due_at)<new Date()).length; return {total:leads.length,new:count('new'),contacted:count('contacted'),qualified:count('qualified'),won,lost,pipeline,overdue,conversion:leads.length?Math.round(won/leads.length*100):0}; },[leads,followups]);
  const hotLeads=useMemo(()=>leads.filter(l=>['qualified','proposal_sent','negotiation'].includes(l.status)).sort((a,b)=>(Number(b.deal_value)||0)-(Number(a.deal_value)||0)).slice(0,6),[leads]);
  const filtered=useMemo(()=>leads.filter(l=>`${l.full_name||''} ${l.email||''} ${l.company||''} ${l.service||''}`.toLowerCase().includes(query.toLowerCase())).slice(0,8),[leads,query]);
  const insights=useMemo(()=>{ const open=stats.total-stats.won-stats.lost; const top=hotLeads[0]; return [stats.overdue>0?`${stats.overdue} follow-up${stats.overdue>1?'s':''} overdue — contact them first.`:'No overdue follow-ups. Keep the pipeline moving.',stats.conversion>=20?`Conversion is ${stats.conversion}%. Prioritize qualified leads for faster wins.`:`Conversion is ${stats.conversion}%. Focus on qualification and follow-up speed.`,top?`${top.full_name} is a priority lead${top.deal_value?` with ₹${Number(top.deal_value).toLocaleString('en-IN')} pipeline`:''}.`:`${open} open opportunities are currently in the pipeline.`]; },[stats,hotLeads]);

  const askAction = (lead: CrmLead, action: "accept"|"reject") => { setConfirmLead(lead); setConfirmAction(action); };
  const confirmStatusChange = async () => {
    if (!confirmLead || !confirmAction) return;
    const lead = confirmLead; const action = confirmAction; const nextStatus = action === "accept" ? "qualified" : "lost";
    setActionBusy(true);
    try {
      await updateLead(lead.id, { status: nextStatus, last_contact_at: action === "accept" ? new Date().toISOString() : lead.last_contact_at });
      await logActivity({ lead_id: lead.id, type: "status", subject: action === "accept" ? "Lead Accepted" : "Lead Rejected", body: action === "accept" ? "Lead accepted from CRM dashboard." : "Lead rejected from CRM dashboard.", outcome: action === "accept" ? "Accepted" : "Rejected" });
      setLeads(prev => prev.map(l => l.id === lead.id ? { ...l, status: nextStatus } : l));
      toast({ title: action === "accept" ? "Lead accepted" : "Lead rejected", description: `${lead.full_name} moved to ${stageLabel(nextStatus)}.` });
      const subject = action === "accept" ? "Your enquiry has been accepted — Crazy SEO Team" : "Update on your enquiry — Crazy SEO Team";
      const body = action === "accept" ? `Hello ${lead.full_name},%0D%0A%0D%0AThank you for contacting Crazy SEO Team. Your enquiry has been accepted by our team. We will contact you shortly regarding ${lead.service || "your requirement"}.%0D%0A%0D%0ARegards,%0D%0ACrazy SEO Team` : `Hello ${lead.full_name},%0D%0A%0D%0AThank you for contacting Crazy SEO Team. We have reviewed your enquiry and will keep your request on record. If you still need assistance, please reply to this email.%0D%0A%0D%0ARegards,%0D%0ACrazy SEO Team`;
      if (lead.email) window.location.href = `mailto:${lead.email}?subject=${encodeURIComponent(subject)}&body=${body}`;
      setConfirmLead(null); setConfirmAction(null);
    } catch (e:any) { toast({title:"Action failed",description:e.message ?? "Could not update lead",variant:"destructive"}); }
    finally { setActionBusy(false); }
  };

  if(loading)return <CrmSkeleton/>;
  if(!leads.length)return <div className="space-y-5"><CrmAttendancePanel/><GlassCard><EmptyState icon={Users} title="No leads yet" hint="Website forms, chatbot and SEO tools can feed leads into this CRM." action={<Link to="/admin/crm/leads"><Button className="rounded-2xl">Create your first lead</Button></Link>}/></GlassCard></div>;
  return <div className="space-y-5">
    <CrmAttendancePanel />
    <AlertDialog open={!!confirmLead} onOpenChange={(open)=>{ if(!open&&!actionBusy){setConfirmLead(null);setConfirmAction(null);} }}>
      <AlertDialogContent>
        <AlertDialogHeader><AlertDialogTitle>{confirmAction === "accept" ? "Accept this lead?" : "Reject this lead?"}</AlertDialogTitle><AlertDialogDescription>{confirmLead ? `${confirmLead.full_name} (${confirmLead.email}) will be moved to ${confirmAction === "accept" ? "Qualified" : "Lost"}. After confirmation, a pre-filled client confirmation email will open.` : ""}</AlertDialogDescription></AlertDialogHeader>
        <AlertDialogFooter><AlertDialogCancel disabled={actionBusy}>Cancel</AlertDialogCancel><AlertDialogAction disabled={actionBusy} onClick={(e)=>{e.preventDefault();void confirmStatusChange();}}>{actionBusy ? "Updating…" : confirmAction === "accept" ? "Accept & notify client" : "Reject & notify client"}</AlertDialogAction></AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>

    <div className="rounded-3xl border border-primary/15 bg-gradient-to-r from-primary/10 via-violet-500/10 to-cyan-500/10 p-5 shadow-sm">
      <div className="flex flex-col xl:flex-row xl:items-center xl:justify-between gap-4"><div><div className="flex items-center gap-2"><Bot className="text-primary" size={20}/><span className="text-xs font-bold uppercase tracking-wider text-primary">AI CRM</span></div><h1 className="text-2xl md:text-3xl font-black mt-1">Sales Command Center</h1><p className="text-sm text-muted-foreground mt-1">Pipeline, follow-ups, revenue and actionable lead intelligence from your CRM.</p></div><div className="flex flex-wrap gap-2"><Button asChild className="rounded-2xl"><Link to="/admin/crm/leads"><UserPlus size={15} className="mr-1"/> Add Lead</Link></Button><Button variant="outline" asChild className="rounded-2xl"><Link to="/admin/crm/follow-ups"><CalendarClock size={15} className="mr-1"/> Follow-ups</Link></Button><Button variant="outline" size="icon" className="rounded-2xl" onClick={load}><RefreshCw size={15}/></Button></div></div>
      <div className="mt-4 flex flex-col md:flex-row gap-3"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search leads, company, service..." className="pl-9 rounded-2xl bg-background/70"/></div><div className="flex gap-1 rounded-2xl border bg-background/50 p-1">{(['7d','30d','90d'] as const).map(r=><button key={r} onClick={()=>setRange(r)} className={`px-3 py-1.5 rounded-xl text-xs font-semibold ${range===r?'bg-primary text-primary-foreground':'text-muted-foreground'}`}>{r.toUpperCase()}</button>)}</div></div>
    </div>
    <div className="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-8 gap-3"><Kpi label="Total Leads" value={stats.total} icon={Users}/><Kpi label="New" value={stats.new} icon={UserPlus} tone="from-sky-500 to-cyan-400"/><Kpi label="Qualified" value={stats.qualified} icon={BadgeCheck} tone="from-violet-500 to-purple-400"/><Kpi label="Won" value={stats.won} icon={Trophy} tone="from-emerald-500 to-teal-400"/><Kpi label="Lost" value={stats.lost} icon={XCircle} tone="from-rose-500 to-orange-400"/><Kpi label="Conversion" value={stats.conversion} suffix="%" icon={Target} tone="from-fuchsia-500 to-pink-400"/><Kpi label="Overdue" value={stats.overdue} icon={BellRing} tone="from-amber-500 to-orange-400"/><Kpi label="Pipeline" value={stats.pipeline} prefix="₹" icon={IndianRupee} tone="from-indigo-500 to-blue-400"/></div>
    <div className="grid gap-4 xl:grid-cols-3"><GlassCard className="xl:col-span-2 p-5"><div className="flex items-center justify-between mb-4"><div><p className="font-black text-lg">AI sales insights</p><p className="text-xs text-muted-foreground">Rule-based intelligence from your live CRM data</p></div><Bot size={22} className="text-primary"/></div><div className="grid gap-3 md:grid-cols-3">{insights.map((x,i)=><div key={i} className="rounded-2xl border bg-muted/30 p-4"><div className="flex gap-2"><Activity size={16} className="text-primary shrink-0 mt-0.5"/><p className="text-sm font-medium">{x}</p></div></div>)}</div></GlassCard><GlassCard className="p-5"><div className="flex items-center justify-between mb-4"><div><p className="font-black text-lg">Pipeline stages</p><p className="text-xs text-muted-foreground">Current opportunity distribution</p></div><Flame size={21} className="text-orange-500"/></div><div className="space-y-3">{CRM_STAGES.map(s=>{const n=leads.filter(l=>l.status===s.id).length; const pct=stats.total?Math.round(n/stats.total*100):0; return <div key={s.id}><div className="flex justify-between text-xs mb-1"><span>{s.label}</span><b>{n}</b></div><div className="h-2 rounded-full bg-muted overflow-hidden"><div className="h-full rounded-full bg-gradient-to-r from-primary to-violet-500" style={{width:`${pct}%`}}/></div></div>})}</div></GlassCard></div>
    <div className="grid gap-4 xl:grid-cols-3"><GlassCard className="xl:col-span-2 p-5"><div className="flex items-center justify-between mb-4"><div><p className="font-black text-lg">Hot leads</p><p className="text-xs text-muted-foreground">Highest-value active opportunities</p></div><Link to="/admin/crm/leads" className="text-xs font-bold text-primary flex items-center gap-1">View all <ArrowRight size={13}/></Link></div><div className="space-y-2">{hotLeads.map(l=><div key={l.id} className="flex items-center justify-between gap-3 rounded-2xl border p-3 hover:bg-muted/40 transition"><div className="min-w-0"><p className="font-bold truncate">{l.full_name}</p><p className="text-xs text-muted-foreground truncate">{l.company||l.service||l.email||'Lead'}</p></div><div className="text-right shrink-0"><p className="font-black text-sm">{l.deal_value?`₹${Number(l.deal_value).toLocaleString('en-IN')}`:'—'}</p><span className="text-[10px] rounded-full bg-primary/10 px-2 py-1 text-primary">{stageLabel(l.status)}</span></div></div>)}{!hotLeads.length&&<p className="text-sm text-muted-foreground">No qualified opportunities yet.</p>}</div></GlassCard><GlassCard className="p-5"><p className="font-black text-lg mb-1">Team performance</p><p className="text-xs text-muted-foreground mb-4">Leads and wins by owner</p><div className="space-y-3">{team.slice(0,6).map(t=>{const mine=leads.filter(l=>l.assigned_to===t.id),won=mine.filter(l=>l.status==='won').length;return <div key={t.id} className="flex items-center justify-between"><div><p className="text-sm font-semibold">{t.name}</p><p className="text-xs text-muted-foreground">{mine.length} leads</p></div><span className="text-xs font-bold text-emerald-600">{won} won</span></div>})}</div></GlassCard></div>
    <GlassCard className="p-5"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3 mb-4"><div><p className="font-black text-lg">Lead workspace</p><p className="text-xs text-muted-foreground">Quick access to your latest matching leads</p></div><div className="flex gap-2"><Button variant="outline" size="sm" className="rounded-2xl" onClick={()=>exportCsv(leads,team)}><Download size={14} className="mr-1"/> CSV</Button><Button variant="outline" size="sm" className="rounded-2xl" onClick={()=>exportExcel(leads,team)}><Download size={14} className="mr-1"/> Excel</Button><Button size="sm" className="rounded-2xl" onClick={()=>exportPdf(leads,team)}><Download size={14} className="mr-1"/> PDF</Button></div></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-muted-foreground"><th className="py-3">Lead</th><th>Company</th><th>Stage</th><th>Value</th><th>Action</th></tr></thead><tbody>{filtered.map(l=><tr key={l.id} className="border-b last:border-0"><td className="py-3 font-semibold">{l.full_name}</td><td>{l.company||'—'}</td><td><span className="rounded-full bg-muted px-2 py-1 text-xs">{stageLabel(l.status)}</span></td><td>{l.deal_value?`₹${Number(l.deal_value).toLocaleString('en-IN')}`:'—'}</td><td><div className="flex flex-wrap gap-1"><Button size="sm" className="h-8 px-2" onClick={()=>askAction(l,"accept")} disabled={l.status === "qualified" || l.status === "won"}><CheckCircle2 size={13} className="mr-1"/>Accept</Button><Button size="sm" variant="destructive" className="h-8 px-2" onClick={()=>askAction(l,"reject")} disabled={l.status === "lost"}><XCircle size={13} className="mr-1"/>Reject</Button><Button size="sm" variant="outline" className="h-8 px-2" asChild><a href={`mailto:${l.email}?subject=${encodeURIComponent("Regarding your enquiry — Crazy SEO Team")}`}><Mail size={13} className="mr-1"/>Message</a></Button></div></td></tr>)}</tbody></table></div></GlassCard>
  </div>;
}
