import { useEffect, useMemo, useState } from "react";
import { Lightbulb, RefreshCw, Search, CheckCircle2, Clock3, XCircle, UserRound, Trash2, Users, MapPin, Globe2, ShieldCheck, ExternalLink, Ban, Unlock, Eye } from "lucide-react";
import { GlassCard } from "@/components/crm/CrmUI";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

type IdeaUser={user_id:string;public_id:string|null;display_name:string|null;first_name:string|null;middle_name:string|null;last_name:string|null;state:string|null;country:string|null;location:string|null;bio:string|null;avatar_url:string|null;cover_url:string|null;website_url:string|null;linkedin_url:string|null;github_url:string|null;instagram_url:string|null;twitter_url:string|null;reputation_points:number;level:number;email:string;auth_created_at:string|null;last_sign_in_at:string|null;post_count:number;follower_count:number;following_count:number;friend_count:number;badges:string[];last_post_at:string|null};
type Idea={id:string;display_name:string;profile_id:string|null;subject:string;title:string;content:string;image_url:string|null;profile_image_url:string|null;device_type:string|null;location:string|null;status:string;created_at:string};
const sanitizeRichHtml=(html:string)=>{
 const doc=new DOMParser().parseFromString(html,"text/html");
 const allowed=["P","H1","H2","H3","STRONG","EM","UL","OL","LI","A","BR"];
 doc.body.querySelectorAll("*").forEach(el=>{
  if(!allowed.includes(el.tagName)){el.replaceWith(...Array.from(el.childNodes));return}
  Array.from(el.attributes).forEach(attr=>{
   if(el.tagName==="A"&&attr.name.toLowerCase()==="href"&&/^https:\\/\\/i.test(attr.value)) return;
   el.removeAttribute(attr.name);
  });
  if(el.tagName==="A"){el.setAttribute("target","_blank");el.setAttribute("rel","noopener noreferrer");}
 });
 return doc.body.innerHTML;
};

async function getFunctionError(error:any, fallback="Request failed"){
  if(!error) return fallback;
  const ctx=error.context;
  if(ctx?.json){
    const body=await ctx.json().catch(()=>null);
    if(body?.error) return body.error;
  }
  return error.message||fallback;
}

export default function CrmIdeasWorkspace(){
 const [ideas,setIdeas]=useState<Idea[]>([]),[users,setUsers]=useState<IdeaUser[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[userSearch,setUserSearch]=useState(""),[selected,setSelected]=useState<IdeaUser|null>(null),[removing,setRemoving]=useState<IdeaUser|null>(null),[busy,setBusy]=useState(false);
 const load=async()=>{setLoading(true);const [ideasRes,usersRes]=await Promise.all([supabase.from("idea_posts").select("id,display_name,profile_id,subject,title,content,image_url,profile_image_url,device_type,location,status,created_at").order("created_at",{ascending:false}),supabase.functions.invoke("crm-ideas-users",{body:{action:"list"}})]);if(ideasRes.error)toast.error(ideasRes.error.message);setIdeas((ideasRes.data||[]) as Idea[]);if(usersRes.error||usersRes.data?.error)toast.error(await getFunctionError(usersRes.error,usersRes.data?.error||"Users could not load"));setUsers((usersRes.data?.users||[]) as IdeaUser[]);setLoading(false)};
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>ideas.filter(i=>{const ok=filter==="all"||i.status===filter,q=query.trim().toLowerCase();return ok&&(!q||[i.title,i.content,i.display_name,i.subject].some(v=>(v||"").toLowerCase().includes(q)))}),[ideas,filter,query]);
 const filteredUsers=useMemo(()=>users.filter(u=>{const q=userSearch.trim().toLowerCase();return !q||[u.display_name,u.first_name,u.last_name,u.email,u.public_id,u.state,u.country].some(v=>(v||"").toLowerCase().includes(q))}),[users,userSearch]);
 const counts={all:ideas.length,pending:ideas.filter(i=>i.status==="pending").length,approved:ideas.filter(i=>i.status==="approved").length,rejected:ideas.filter(i=>i.status==="rejected").length};
 const deleteUser=async()=>{if(!removing)return;setBusy(true);try{const {data,error}=await supabase.functions.invoke("crm-ideas-users",{body:{action:"delete",user_id:removing.user_id}});if(error||data?.error)throw new Error(await getFunctionError(error,data?.error||"Could not delete user"));toast.success("Ideas account and CRM account data deleted permanently.");setRemoving(null);setSelected(null);await load()}catch(e:any){toast.error(e?.message||"Could not delete user")}finally{setBusy(false)}};
 return <div className="space-y-5">
  <VerificationModeration />
  <GlassCard className="p-6"><div className="flex flex-col xl:flex-row xl:items-center xl:justify-between gap-4"><div><div className="flex items-center gap-2 text-primary text-xs font-black uppercase tracking-wider"><Lightbulb size={18}/> Ideas CRM Workspace</div><h2 className="text-2xl font-black mt-1">Ideas Community Management</h2><p className="text-sm text-muted-foreground mt-1">Community users, profiles, posts, social activity and moderation in one place.</p></div><Button variant="outline" className="rounded-2xl" onClick={load}><RefreshCw size={14} className="mr-2"/>Refresh</Button></div></GlassCard>
  <div className="grid grid-cols-2 lg:grid-cols-5 gap-3">
   <div className="rounded-2xl border bg-card p-4"><Users size={18} className="text-primary"/><p className="text-xs text-muted-foreground mt-2">Total Users</p><p className="text-2xl font-black">{users.length}</p></div>
   <div className="rounded-2xl border bg-card p-4"><Lightbulb size={18} className="text-primary"/><p className="text-xs text-muted-foreground mt-2">Total Ideas</p><p className="text-2xl font-black">{counts.all}</p></div>
   <button onClick={()=>setFilter("pending")} className="rounded-2xl border bg-card p-4 text-left"><Clock3 size={18} className="text-amber-500"/><p className="text-xs text-muted-foreground mt-2">Pending</p><p className="text-2xl font-black">{counts.pending}</p></button>
   <div className="rounded-2xl border bg-card p-4"><CheckCircle2 size={18} className="text-emerald-500"/><p className="text-xs text-muted-foreground mt-2">Approved</p><p className="text-2xl font-black">{counts.approved}</p></div>
   <div className="rounded-2xl border bg-card p-4"><Globe2 size={18} className="text-violet-500"/><p className="text-xs text-muted-foreground mt-2">Countries</p><p className="text-2xl font-black">{new Set(users.map(u=>u.country).filter(Boolean)).size}</p></div>
  </div>
  <GlassCard className="p-5"><div className="flex items-center justify-between gap-3 mb-4"><div><h3 className="font-black text-lg">Community Users</h3><p className="text-xs text-muted-foreground">Full public profile + account activity. Delete permanently removes the account from Ideas and CRM.</p></div><Badge variant="secondary">{filteredUsers.length} shown</Badge></div><div className="relative"><Search size={16} className="absolute left-3 top-3 text-muted-foreground"/><Input value={userSearch} onChange={e=>setUserSearch(e.target.value)} placeholder="Search user, email, public ID, state or country..." className="rounded-2xl pl-9"/></div></GlassCard>
  <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{loading?<GlassCard className="p-6"><p className="text-sm text-muted-foreground">Loading community users...</p></GlassCard>:filteredUsers.map(u=><GlassCard key={u.user_id} className="p-5"><div className="flex items-start gap-3"><img src={u.avatar_url||"/favicon.ico"} alt="" className="h-12 w-12 rounded-2xl object-cover bg-muted" onError={e=>{e.currentTarget.style.display="none"}}/><div className="min-w-0 flex-1"><p className="font-black truncate">{[u.first_name,u.middle_name,u.last_name].filter(Boolean).join(" ")||u.display_name||"Unnamed User"}</p><p className="text-xs text-muted-foreground truncate">{u.email||"No email"}</p><div className="flex flex-wrap gap-1 mt-2"><Badge variant="outline">{u.public_id||"No Public ID"}</Badge><Badge>Level {u.level||1}</Badge></div></div></div><div className="grid grid-cols-4 gap-2 mt-4 text-center"><div className="rounded-xl bg-muted/50 p-2"><p className="text-[10px] text-muted-foreground">Posts</p><p className="font-black">{u.post_count}</p></div><div className="rounded-xl bg-muted/50 p-2"><p className="text-[10px] text-muted-foreground">Followers</p><p className="font-black">{u.follower_count}</p></div><div className="rounded-xl bg-muted/50 p-2"><p className="text-[10px] text-muted-foreground">Following</p><p className="font-black">{u.following_count}</p></div><div className="rounded-xl bg-muted/50 p-2"><p className="text-[10px] text-muted-foreground">Friends</p><p className="font-black">{u.friend_count}</p></div></div><div className="mt-3 text-xs text-muted-foreground space-y-1"><p className="flex gap-2"><MapPin size={13}/>{[u.state,u.country].filter(Boolean).join(", ")||u.location||"Location not shared"}</p><p>Reputation: <b>{u.reputation_points}</b> · Badges: <b>{u.badges.length}</b></p><p>Last login: {u.last_sign_in_at?new Date(u.last_sign_in_at).toLocaleString():"Never"}</p></div><div className="mt-4 flex gap-2"><Button variant="outline" className="flex-1" onClick={()=>setSelected(u)}>Full details</Button><Button variant="destructive" size="icon" onClick={()=>setRemoving(u)} title="Delete user"><Trash2 size={15}/></Button></div></GlassCard>)}</div>
  <GlassCard className="p-4"><div className="relative"><Search size={16} className="absolute left-3 top-3 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ideas, people, subject..." className="rounded-2xl pl-9"/></div></GlassCard>
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[["all","All Ideas",Lightbulb],["pending","Pending",Clock3],["approved","Approved",CheckCircle2],["rejected","Rejected",XCircle]].map(([key,label,Icon])=><button key={key} onClick={()=>setFilter(key as string)} className={filter===key?"rounded-2xl border border-primary bg-primary/5 p-4 text-left":"rounded-2xl border p-4 text-left hover:border-primary/40"}><Icon size={18} className="text-primary"/><p className="text-xs text-muted-foreground mt-2">{label}</p><p className="text-2xl font-black">{counts[key as keyof typeof counts]}</p></button>)}</div>
  <div className="space-y-3">{loading?<GlassCard className="p-6"><p className="text-sm text-muted-foreground">Loading ideas...</p></GlassCard>:filtered.length===0?<GlassCard className="p-8 text-center"><Lightbulb className="mx-auto text-muted-foreground" size={28}/><p className="font-bold mt-2">No ideas found</p></GlassCard>:filtered.map(i=><GlassCard key={i.id} className="p-5"><div className="flex gap-4">{i.profile_image_url?<img src={i.profile_image_url} alt="" className="h-11 w-11 rounded-full object-cover shrink-0"/>:<div className="h-11 w-11 rounded-full bg-primary/10 flex items-center justify-center shrink-0"><UserRound size={18} className="text-primary"/></div>}<div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="font-black">{i.display_name}</span><span className="text-xs rounded-full bg-muted px-2 py-1">{i.subject}</span><span className="text-xs rounded-full border px-2 py-1">{i.status}</span></div><h3 className="text-lg font-black mt-2">{i.title}</h3><div className="rich-content mt-3 max-w-none text-sm leading-7 text-muted-foreground [&_h1]:my-5 [&_h1]:text-3xl [&_h1]:font-black [&_h1]:tracking-tight [&_h2]:my-4 [&_h2]:text-2xl [&_h2]:font-bold [&_h3]:my-3 [&_h3]:text-xl [&_h3]:font-bold [&_p]:my-2 [&_strong]:font-bold [&_em]:italic [&_a]:font-semibold [&_a]:text-primary [&_a]:underline [&_ul]:my-3 [&_ul]:list-disc [&_ul]:pl-6 [&_ol]:my-3 [&_ol]:list-decimal [&_ol]:pl-6" dangerouslySetInnerHTML={{__html:sanitizeRichHtml(i.content)}} /><div className="text-xs text-muted-foreground mt-3">{i.location||"Location not shared"}{i.device_type?" • "+i.device_type:""} • {new Date(i.created_at).toLocaleString()}</div></div></div>{i.image_url&&<img src={i.image_url} alt="" className="mt-4 w-full max-h-72 rounded-2xl object-cover border"/>}</GlassCard>)}</div>
  <Dialog open={!!selected} onOpenChange={o=>!o&&setSelected(null)}><DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Complete Ideas User Details</DialogTitle></DialogHeader>{selected&&<div className="space-y-5"><div className="flex gap-4 items-center"><img src={selected.avatar_url||"/favicon.ico"} className="h-20 w-20 rounded-3xl object-cover bg-muted" alt=""/><div><h3 className="text-xl font-black">{[selected.first_name,selected.middle_name,selected.last_name].filter(Boolean).join(" ")||selected.display_name}</h3><p className="text-sm text-muted-foreground">{selected.email}</p><p className="text-xs font-bold text-primary mt-1">{selected.public_id||"No Public ID"} · Level {selected.level} · {selected.reputation_points} reputation</p></div></div><div className="grid grid-cols-2 gap-3 text-sm">{[["First Name",selected.first_name],["Middle Name",selected.middle_name],["Last Name",selected.last_name],["State",selected.state],["Country",selected.country],["Location",selected.location],["Posts",selected.post_count],["Followers",selected.follower_count],["Following",selected.following_count],["Friends",selected.friend_count],["Joined",selected.auth_created_at?new Date(selected.auth_created_at).toLocaleString():"—"],["Last Login",selected.last_sign_in_at?new Date(selected.last_sign_in_at).toLocaleString():"Never"],["Last Post",selected.last_post_at?new Date(selected.last_post_at).toLocaleString():"—"],["Badges",selected.badges.join(", ")||"None"]].map(([k,v])=><div key={String(k)} className="rounded-xl border p-3"><p className="text-[10px] uppercase text-muted-foreground">{k}</p><p className="font-semibold break-words">{String(v??"—")}</p></div>)}</div>{selected.bio&&<div className="rounded-2xl border p-4"><p className="text-xs font-bold uppercase text-muted-foreground">Bio</p><p className="mt-1 text-sm whitespace-pre-wrap">{selected.bio}</p></div>}<div className="flex flex-wrap gap-2">{[["Website",selected.website_url],["LinkedIn",selected.linkedin_url],["GitHub",selected.github_url],["Instagram",selected.instagram_url],["X / Twitter",selected.twitter_url]].filter(([,v])=>v).map(([k,v])=><a key={String(k)} href={String(v)} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 rounded-xl border px-3 py-2 text-xs font-semibold hover:bg-muted"><ExternalLink size={12}/>{k}</a>)}</div><div className="rounded-2xl border border-destructive/20 bg-destructive/5 p-4 text-sm"><div className="flex items-center gap-2 font-bold text-destructive"><ShieldCheck size={16}/>Danger zone</div><p className="text-muted-foreground mt-1">Deleting permanently removes the Ideas account, its community data, and its CRM membership.</p><Button variant="destructive" className="mt-3" onClick={()=>setRemoving(selected)}><Trash2 size={15} className="mr-2"/>Delete user</Button></div></div>}</DialogContent></Dialog>
  <AlertDialog open={!!removing} onOpenChange={o=>!o&&!busy&&setRemoving(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete {removing?.display_name||removing?.email}?</AlertDialogTitle><AlertDialogDescription>This permanently deletes the Ideas account, linked Ideas data, storage files and CRM membership. This cannot be undone.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={deleteUser}>{busy?"Deleting…":"Delete permanently"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
function VerificationModeration(){
 const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[banReason,setBanReason]=useState<Record<string,string>>({});
 const load=async()=>{setLoading(true);const {data,error}=await supabase.from("idea_verification_requests").select("id,user_id,selfie_path,status,rejection_reason,created_at").order("created_at",{ascending:false});if(error){toast.error(error.message);setLoading(false);return}const ids=(data||[]).map(x=>x.user_id);let profiles:any[]=[];if(ids.length){const p=await supabase.from("idea_profiles").select("user_id,display_name,first_name,last_name,email,public_id,avatar_url,verified,account_status,ban_reason,banned_until").in("user_id",ids);profiles=p.data||[]}const out=await Promise.all((data||[]).map(async r=>{const p=profiles.find(x=>x.user_id===r.user_id);const signed=await supabase.storage.from("idea-verification").createSignedUrl(r.selfie_path,600);return {...r,profile:p,signedUrl:signed.data?.signedUrl||null}}));setRows(out);setLoading(false)};
 useEffect(()=>{load()},[]);
 const review=async(row:any,status:"verified"|"rejected")=>{setBusy(row.id);const {data:{user}}=await supabase.auth.getUser();const reason=status==="rejected"?(prompt("Reason for rejection?")||"Verification requirements not met."):null;if(status==="rejected"&&reason===null){setBusy(null);return}const a=await supabase.from("idea_verification_requests").update({status,rejection_reason:reason,reviewed_by:user?.id||null,reviewed_at:new Date().toISOString()}).eq("id",row.id);if(a.error){toast.error(a.error.message);setBusy(null);return}const b=await supabase.from("idea_profiles").update({verified:status==="verified",verification_status:status}).eq("user_id",row.user_id);if(b.error)toast.error(b.error.message);else toast.success(status==="verified"?"User verified.":"Verification rejected.");await load();setBusy(null)};
 const ban=async(row:any)=>{const reason=banReason[row.user_id]?.trim()||"Community policy violation";const {error}=await supabase.from("idea_profiles").update({account_status:"banned",ban_reason:reason,banned_until:null}).eq("user_id",row.user_id);if(error)toast.error(error.message);else{toast.success("Account banned.");await load()}};
 const unban=async(row:any)=>{const {error}=await supabase.from("idea_profiles").update({account_status:"active",ban_reason:null,banned_until:null}).eq("user_id",row.user_id);if(error)toast.error(error.message);else{toast.success("Account unbanned.");await load()}};
 return <GlassCard className="p-5"><div className="flex items-center justify-between gap-3"><div><div className="flex items-center gap-2"><ShieldCheck className="text-primary" size={19}/><h3 className="font-black text-lg">Verification & Account Safety</h3></div><p className="text-xs text-muted-foreground mt-1">Review private selfies, verify profiles, or ban/unban community accounts.</p></div><Button variant="outline" size="sm" onClick={load}>Refresh</Button></div>{loading?<p className="mt-4 text-sm text-muted-foreground">Loading verification requests…</p>:rows.length===0?<div className="mt-4 rounded-2xl border border-dashed p-5 text-center text-sm text-muted-foreground">No verification requests yet.</div>:<div className="mt-4 space-y-3">{rows.map(r=><div key={r.id} className="rounded-2xl border p-4"><div className="flex flex-col gap-4 lg:flex-row lg:items-center"><div className="h-28 w-28 shrink-0 overflow-hidden rounded-2xl bg-muted">{r.signedUrl?<img src={r.signedUrl} alt="Private verification selfie" className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-xs text-muted-foreground">Selfie unavailable</div>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-black">{r.profile?.display_name||[r.profile?.first_name,r.profile?.last_name].filter(Boolean).join(" ")||"Ideas User"}</p><Badge variant={r.status==="verified"?"default":"outline"}>{r.status}</Badge>{r.profile?.account_status==="banned"&&<Badge variant="destructive">Banned</Badge>}</div><p className="mt-1 text-xs text-muted-foreground">{r.profile?.email||"No email"} · {r.profile?.public_id||"No Public ID"}</p><p className="mt-2 text-xs text-muted-foreground">Submitted {new Date(r.created_at).toLocaleString()}</p><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" onClick={()=>review(r,"verified")} disabled={busy===r.id||r.status==="verified"}><ShieldCheck size={14} className="mr-1"/>Verify</Button><Button size="sm" variant="outline" onClick={()=>review(r,"rejected")} disabled={busy===r.id||r.status==="rejected"}><XCircle size={14} className="mr-1"/>Reject</Button>{r.profile?.account_status==="banned"?<Button size="sm" variant="outline" onClick={()=>unban(r)}><Unlock size={14} className="mr-1"/>Unban</Button>:<Button size="sm" variant="destructive" onClick={()=>ban(r)}><Ban size={14} className="mr-1"/>Ban</Button>}</div><div className="mt-3 flex gap-2"><Input placeholder="Ban reason" value={banReason[r.user_id]||""} onChange={e=>setBanReason(v=>({...v,[r.user_id]:e.target.value}))} className="max-w-md"/></div></div></div></div>)}</div>}</GlassCard>;
}
