import { useEffect, useMemo, useState } from "react";
import { Lightbulb, RefreshCw, Search, CheckCircle2, Clock3, XCircle, UserRound } from "lucide-react";
import { GlassCard } from "@/components/crm/CrmUI";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "@/hooks/use-toast";
type Idea={id:string;display_name:string;profile_id:string|null;subject:string;title:string;content:string;image_url:string|null;profile_image_url:string|null;device_type:string|null;location:string|null;status:string;created_at:string};
export default function CrmIdeasWorkspace(){
 const [ideas,setIdeas]=useState<Idea[]>([]); const [loading,setLoading]=useState(true); const [query,setQuery]=useState(""); const [filter,setFilter]=useState("all");
 const load=async()=>{setLoading(true);const {data,error}=await supabase.from("idea_posts").select("id,display_name,profile_id,subject,title,content,image_url,profile_image_url,device_type,location,status,created_at").order("created_at",{ascending:false});if(error){toast({title:"Ideas could not load",description:error.message,variant:"destructive"});setIdeas([])}else setIdeas((data||[]) as Idea[]);setLoading(false)};
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>ideas.filter(i=>{const ok=filter==="all"||i.status===filter;const q=query.trim().toLowerCase();return ok&&(!q||[i.title,i.content,i.display_name,i.subject].some(v=>(v||"").toLowerCase().includes(q))) }),[ideas,filter,query]);
 const counts={all:ideas.length,pending:ideas.filter(i=>i.status==="pending").length,approved:ideas.filter(i=>i.status==="approved").length,rejected:ideas.filter(i=>i.status==="rejected").length};
 return <div className="space-y-5">
  <GlassCard className="p-6"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><div className="flex items-center gap-2 text-primary text-xs font-black uppercase tracking-wider"><Lightbulb size={18}/> Ideas Workspace</div><h2 className="text-2xl font-black mt-1">CRM Ideas & Innovation</h2><p className="text-sm text-muted-foreground mt-1">Review community ideas, discover useful suggestions and track idea status from one dedicated CRM page.</p></div><Button variant="outline" className="rounded-2xl" onClick={load}><RefreshCw size={14} className="mr-2"/>Refresh</Button></div></GlassCard>
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[["all","Total Ideas",Lightbulb],["pending","Pending",Clock3],["approved","Approved",CheckCircle2],["rejected","Rejected",XCircle]].map(([key,label,Icon])=><button key={key} onClick={()=>setFilter(key as string)} className={filter===key?"rounded-2xl border border-primary bg-primary/5 p-4 text-left":"rounded-2xl border p-4 text-left hover:border-primary/40"}><Icon size={18} className="text-primary"/><p className="text-xs text-muted-foreground mt-2">{label}</p><p className="text-2xl font-black">{counts[key as keyof typeof counts]}</p></button>)}</div>
  <GlassCard className="p-4"><div className="relative"><Search size={16} className="absolute left-3 top-3 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ideas, people, subject..." className="rounded-2xl pl-9"/></div></GlassCard>
  <div className="space-y-3">{loading?<GlassCard className="p-6"><p className="text-sm text-muted-foreground">Loading ideas...</p></GlassCard>:filtered.length===0?<GlassCard className="p-8 text-center"><Lightbulb className="mx-auto text-muted-foreground" size={28}/><p className="font-bold mt-2">No ideas found</p><p className="text-sm text-muted-foreground mt-1">Try another filter or search.</p></GlassCard>:filtered.map(i=><GlassCard key={i.id} className="p-5"><div className="flex gap-4">{i.profile_image_url?<img src={i.profile_image_url} alt="" className="h-11 w-11 rounded-full object-cover shrink-0"/>:<div className="h-11 w-11 rounded-full bg-primary/10 flex items-center justify-center shrink-0"><UserRound size={18} className="text-primary"/></div>}<div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="font-black">{i.display_name}</span><span className="text-xs rounded-full bg-muted px-2 py-1">{i.subject}</span><span className="text-xs rounded-full border px-2 py-1">{i.status}</span></div><h3 className="text-lg font-black mt-2">{i.title}</h3><p className="text-sm text-muted-foreground mt-1 whitespace-pre-wrap">{i.content}</p><div className="text-xs text-muted-foreground mt-3">{i.location||"Location not shared"} {i.device_type?" • "+i.device_type:""} • {new Date(i.created_at).toLocaleString()}</div></div></div>{i.image_url&&<img src={i.image_url} alt="" className="mt-4 w-full max-h-72 rounded-2xl object-cover border"/>}</GlassCard>)}</div>
 </div>;
}