import { useCallback, useEffect, useMemo, useState } from "react";
import { Copy, RefreshCw, Trash2, Code2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { GlassCard, EmptyState, CrmSkeleton } from "@/components/crm/CrmUI";
import { deleteSchemaRecord, fetchSchemaRecords, type SchemaRecord } from "@/lib/schemaRecords";

export default function CrmSchemaRecords() {
  const [records, setRecords] = useState<SchemaRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState("");

  const load = useCallback(async () => {
    setLoading(true);
    try { setRecords(await fetchSchemaRecords()); }
    catch (e: any) { toast.error(e?.message ?? "Unable to load schema records"); }
    finally { setLoading(false); }
  }, []);

  useEffect(() => { void load(); }, [load]);

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return records;
    return records.filter(r => [r.name, r.schema_type, r.url, r.author].some(v => v.toLowerCase().includes(q)));
  }, [records, query]);

  const remove = async (id: string) => {
    try { await deleteSchemaRecord(id); setRecords(v => v.filter(r => r.id !== id)); toast.success("Schema record deleted"); }
    catch (e: any) { toast.error(e?.message ?? "Delete failed"); }
  };

  const copy = async (r: SchemaRecord) => {
    await navigator.clipboard.writeText(JSON.stringify(r.schema_json, null, 2));
    toast.success("Schema JSON copied");
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2"><Code2 className="h-6 w-6" /> Schema Records</h1>
          <p className="text-sm text-muted-foreground">CRM-connected JSON-LD records generated by your SEO tools.</p>
        </div>
        <Button variant="outline" onClick={() => void load()} disabled={loading}><RefreshCw className="h-4 w-4 mr-2" /> Refresh</Button>
      </div>

      <GlassCard className="p-4">
        <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
          <Input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search name, type, URL or author..." className="md:max-w-md" />
          <Badge variant="secondary">{filtered.length} records</Badge>
        </div>
      </GlassCard>

      {loading ? <CrmSkeleton /> : filtered.length === 0 ? (
        <EmptyState title={query ? "No matching schema records" : "No schema records yet"} description={query ? "Try another search." : "Generate a schema from the Schema Generator and save it to CRM."} />
      ) : (
        <div className="space-y-3">
          {filtered.map(r => (
            <GlassCard key={r.id} className="p-4">
              <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
                <div className="min-w-0 space-y-2">
                  <div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold truncate">{r.name || "Untitled schema"}</h2><Badge>{r.schema_type}</Badge></div>
                  {r.url && <p className="text-xs text-muted-foreground break-all">{r.url}</p>}
                  <p className="text-xs text-muted-foreground">Author: {r.author || "Crazy SEO Team"} · {new Date(r.created_at).toLocaleString()}</p>
                  <pre className="max-h-48 overflow-auto rounded-md border bg-secondary/40 p-3 text-[11px] whitespace-pre-wrap break-all">{JSON.stringify(r.schema_json, null, 2)}</pre>
                </div>
                <div className="flex shrink-0 gap-2">
                  <Button size="sm" variant="outline" onClick={() => void copy(r)}><Copy className="h-4 w-4 mr-1" /> Copy</Button>
                  <Button size="sm" variant="destructive" onClick={() => void remove(r.id)}><Trash2 className="h-4 w-4 mr-1" /> Delete</Button>
                </div>
              </div>
            </GlassCard>
          ))}
        </div>
      )}
    </div>
  );
}
