import { useEffect, useMemo, useState } from "react";
import { Cpu, Code2, Bug, Rocket, Server, Users2, RefreshCw, Plus, CheckCircle2, Circle, ArrowRight } from "lucide-react";
import { Link, useSearchParams } from "react-router-dom";
import { GlassCard } from "@/components/crm/CrmUI";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "@/hooks/use-toast";
import { fetchTeam, type TeamMember } from "@/lib/crm";
type Item={id:string;title:string;description:string|null;status:string;priority:string;due_date:string|null;created_at:string};
const functions=[["software","Software",Cpu],["development","Development",Code2],["bugs","Bugs",Bug],["deployments","Deployments",Rocket],["infrastructure","Infrastructure",Server]] as const;
export default function CrmTechnologyWorkspace(){
 const [params,setParams]=useSearchParams(); const view=params.get("view")||"overview";
 const [team,setTeam]=useState<TeamMember[]>([]); const [items,setItems]=useState<Item[]>([]); const [title,setTitle]=useState(""); const [description,setDescription]=useState(""); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false);
 const load=async()=>{setLoading(true);const [t,i]=await Promise.all([fetchTeam(),supabase.from("crm_workspace_items").select("id,title,description,status,priority,due_date,created_at").eq("module","technology").order("created_at",{ascending:false})]);if(i.error)toast({title:"Technology data could not load",description:i.error.message,variant:"destructive"});setTeam(t||[]);setItems((i.data||[]) as Item[]);setLoading(false)};
 useEffect(()=>{void load()},[]);
 const active=team.filter(x=>x.status!=="inactive"); const open=items.filter(x=>!["completed","done","closed"].includes(x.status)).length; const done=items.length-open;
 const add=async()=>{if(!title.trim())return toast({title:"Title required",variant:"destructive"});setBusy(true);const {data:u}=await supabase.auth.getUser();if(!u.user){setBusy(false);return toast({title:"Login required",variant:"destructive"})}const {data,error}=await supabase.from("crm_workspace_items").insert({module:"technology",title:title.trim(),description:description.trim()||null,status:"open",priority:"medium",created_by:u.user.id}).select("id,title,description,status,priority,due_date,created_at").single();if(error)toast({title:"Could not save",description:error.message,variant:"destructive"});else{setItems(v=>[data as Item,...v]);setTitle("");setDescription("");toast({title:"Technology item added"})}setBusy(false)};
 const toggle=async(x:Item)=>{const next=["completed","done","closed"].includes(x.status)?"open":"completed";const {error}=await supabase.from("crm_workspace_items").update({status:next,updated_at:new Date().toISOString()}).eq("id",x.id);if(error)toast({title:"Update failed",description:error.message,variant:"destructive"});else setItems(v=>v.map(i=>i.id===x.id?{...i,status:next}:i))};
 const selected=functions.find(x=>x[0]===view); const filtered=useMemo(()=>selected?items.filter(x=>((x.title+" "+(x.description||"")).toLowerCase().includes(selected[1].toLowerCase()))):items,[items,selected]);
 return <div className="space-y-5">
  <GlassCard className="p-6"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><div className="flex items-center gap-2 text-primary text-xs font-black uppercase tracking-wider"><Cpu size={18}/> Technology Workspace</div><h2 className="text-2xl font-black mt-1">Technology Operations Center</h2><p className="text-sm text-muted-foreground mt-1">Software, development, bugs, deployments and infrastructure in one dedicated workspace.</p></div><Button variant="outline" className="rounded-2xl" onClick={load}><RefreshCw size={14} className="mr-2"/>Refresh</Button></div></GlassCard>
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><GlassCard className="p-4"><p className="text-xs text-muted-foreground">Active Team</p><p className="text-2xl font-black">{active.length}</p></GlassCard><GlassCard className="p-4"><p className="text-xs text-muted-foreground">Open Tech Items</p><p className="text-2xl font-black">{open}</p></GlassCard><GlassCard className="p-4"><p className="text-xs text-muted-foreground">Completed</p><p className="text-2xl font-black">{done}</p></GlassCard><GlassCard className="p-4"><p className="text-xs text-muted-foreground">Functions</p><p className="text-2xl font-black">5</p></GlassCard></div>
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{functions.map(([key,label,Icon])=><button key={key} onClick={()=>setParams({view:key})} className={view===key ? "rounded-2xl border p-4 text-left transition border-primary bg-primary/5 shadow-sm" : "rounded-2xl border p-4 text-left transition hover:border-primary/40"}><Icon size={19} className="text-primary"/><p className="font-black mt-2">{label}</p><p className="text-xs text-muted-foreground">Open workspace <ArrowRight size={11} className="inline"/></p></button>)}</div>
  {view==="overview"&&<GlassCard className="p-5"><div className="flex items-center gap-2 mb-4"><Users2 size={19} className="text-primary"/><p className="font-black text-lg">Technology Team</p></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{active.map(m=><div key={m.id} className="rounded-2xl border p-3 flex items-center gap-3">{m.photo_url?<img src={m.photo_url} className="h-10 w-10 rounded-full object-cover" alt=""/>:<div className="h-10 w-10 rounded-full bg-muted flex items-center justify-center text-xs font-bold">{m.name.slice(0,2).toUpperCase()}</div>}<div className="min-w-0"><p className="font-bold truncate">{m.name}</p><p className="text-xs text-muted-foreground truncate">{m.position}</p></div></div>)}</div></GlassCard>}
  {view!=="overview"&&<><GlassCard className="p-5"><p className="font-black text-lg">{selected?.[1]} Workspace</p><p className="text-xs text-muted-foreground mt-1">Track {selected?.[1].toLowerCase()} work without mixing it with other CRM modules.</p><div className="grid gap-3 mt-4"><Input value={title} onChange={e=>setTitle(e.target.value)} placeholder={"Add "+selected?.[1]+" item title *"} className="rounded-2xl"/><Textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description / notes" className="rounded-2xl"/><Button onClick={add} disabled={busy} className="rounded-2xl w-fit"><Plus size={15} className="mr-2"/>{busy?"Saving…":"Add Item"}</Button></div></GlassCard><GlassCard className="p-5"><p className="font-black mb-4">{selected?.[1]} Activity</p>{loading?<p className="text-sm text-muted-foreground">Loading…</p>:filtered.length===0?<p className="text-sm text-muted-foreground">No matching items yet.</p>:<div className="space-y-2">{filtered.map(x=><div key={x.id} className="rounded-2xl border p-4 flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><p className="font-bold">{x.title}</p>{["completed","done","closed"].includes(x.status)?<CheckCircle2 size={15} className="text-emerald-600"/>:<Circle size={15} className="text-primary"/>}</div>{x.description&&<p className="text-sm text-muted-foreground mt-1">{x.description}</p>}</div><Button size="sm" variant="outline" className="rounded-xl shrink-0" onClick={()=>toggle(x)}>Toggle</Button></div>)}</div>}</GlassCard></>}
 </div>
}