import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft, Copy, MapPin, Phone, ShieldCheck, Video, Smartphone, Monitor, Clock3 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { getListing, getLiveListing, getMedia, type ClassifiedListing } from "@/lib/classifiedStorage";

export default function ClassifiedListing(){
 const {id=""}=useParams(); const [listing,setListing]=useState<ClassifiedListing|null>(null); const [media,setMedia]=useState<string[]>([]); const [video,setVideo]=useState("");
 useEffect(()=>{let active=true;(async()=>{const remote=await getLiveListing(id);const local=remote||getListing(id.split("-").slice(0,5).join("-"));if(!active||!local)return;setListing(local);if(local.photos?.some(p=>p.url)){setMedia(local.photos.map(p=>p.url).filter(Boolean) as string[])}else{const urls:string[]=[];for(let i=0;i<local.photos.length;i++){const f=await getMedia(`${local.id}-${i}-${local.photos[i].name}`);if(f)urls.push(URL.createObjectURL(f))}if(active)setMedia(urls)}if(local.video?.url)setVideo(local.video.url);else if(local.video){const f=await getMedia(`${local.id}-0-${local.video.name}`);if(f&&active)setVideo(URL.createObjectURL(f))}})();return()=>{active=false}},[id]);
 if(!listing)return <div className="min-h-screen bg-slate-50 pt-36"><div className="mx-auto max-w-xl px-4 text-center"><h1 className="text-2xl font-black">Listing not found</h1><p className="mt-2 text-slate-500">This listing may be pending or unavailable.</p><Button asChild className="mt-5"><Link to="/classifieds">Back to Classifieds</Link></Button></div></div>;
 const share=()=>navigator.clipboard?.writeText(window.location.href);
 const published=new Date(listing.createdAt);
 return <div className="min-h-screen bg-slate-50 pt-32 pb-16"><div className="mx-auto max-w-5xl px-4 lg:px-6"><Link to="/classifieds" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft size={16}/> Back</Link><div className="mt-5 grid gap-6 lg:grid-cols-[1.5fr_1fr]"><section className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="grid grid-cols-2 gap-2 bg-slate-100 p-2">{media.length?media.map((src,i)=><img key={`${src}-${i}`} src={src} alt={`${listing.title} photo ${i+1}`} className="aspect-square w-full rounded-2xl object-cover"/>):<div className="col-span-2 flex aspect-video items-center justify-center text-slate-400">No photos</div>}</div>{video&&<div className="border-t p-4"><div className="mb-2 flex items-center gap-2 font-bold"><Video size={17}/> Listing video</div><video src={video} controls className="max-h-96 w-full rounded-2xl bg-black"/></div>}</section><aside className="rounded-3xl border bg-white p-6 shadow-sm"><span className="text-xs font-bold uppercase tracking-[.2em] text-blue-600">{listing.category}</span><h1 className="mt-2 text-3xl font-black">{listing.title}</h1><p className="mt-3 text-2xl font-black">{listing.price||"Price on request"}</p><p className="mt-3 flex items-center gap-2 text-sm text-slate-500"><MapPin size={16}/>{listing.location||"Location not specified"}</p><div className="mt-3 flex flex-wrap gap-2 text-xs text-slate-500"><span className="inline-flex items-center gap-1 rounded-full bg-slate-100 px-2.5 py-1"><Clock3 size={13}/> Posted {published.toLocaleString()}</span><span className="inline-flex items-center gap-1 rounded-full bg-slate-100 px-2.5 py-1">{listing.source==="mobile"?<Smartphone size={13}/>:<Monitor size={13}/>} {listing.source==="mobile"?"Mobile":"Web"}</span></div><div className="mt-6 rounded-2xl bg-blue-50 p-4"><div className="flex items-center gap-2 font-bold text-blue-800"><ShieldCheck size={17}/> Seller: {listing.seller}</div><p className="mt-2 whitespace-pre-wrap text-sm text-slate-700">{listing.description}</p></div><div className="mt-5 grid gap-2"><Button asChild className="rounded-xl"><a href={`tel:${listing.phone}`}><Phone size={16}/> Contact seller</a></Button><Button variant="outline" onClick={share} className="rounded-xl"><Copy size={16}/> Copy live link</Button></div></aside></div></div></div>;
}
