import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { CalendarDays, Clock, MapPin, ExternalLink, Loader2, Radio } from "lucide-react";
export default function IdeasEvents(){
 const [events,setEvents]=useState<any[]>([]),[loading,setLoading]=useState(true),[me,setMe]=useState<string|null>(null),[rsvps,setRsvps]=useState<Record<string,string>>({});
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();setMe(user?.id||null);const {data,error}=await supabase.from("idea_posts").select("*").eq("status","approved").eq("post_type","event").order("event_start",{ascending:true});if(!error)setEvents(data||[]);if(user?.id&&data?.length){const {data:r}=await supabase.from("idea_event_rsvps").select("post_id,status").eq("user_id",user.id).in("post_id",data.map(x=>x.id));setRsvps(Object.fromEntries((r||[]).map(x=>[x.post_id,x.status])))}setLoading(false)})()},[]);
 const rsvp=async(post:any,next:"going"|"interested")=>{if(!me)return;const current=rsvps[post.id];if(current===next){await supabase.from("idea_event_rsvps").delete().eq("post_id",post.id).eq("user_id",me);setRsvps(v=>({...v,[post.id]:""}));return}await supabase.from("idea_event_rsvps").upsert({post_id:post.id,user_id:me,status:next},{onConflict:"post_id,user_id"});setRsvps(v=>({...v,[post.id]:next}))};
 const state=(e:any)=>{const now=Date.now(),s=e.event_start?new Date(e.event_start).getTime():0,end=e.event_end?new Date(e.event_end).getTime():s+3600000;return now>=s&&now<=end?"live":now<s?"upcoming":"ended"};
 return <div className="min-h-screen bg-[#f8f9fc] dark:bg-background"><div className="mx-auto max-w-5xl px-4 py-8"><div className="mb-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">ANVYA Events</p><h1 className="mt-1 text-3xl font-black">Live & Upcoming Events</h1><p className="mt-2 text-sm text-muted-foreground">Discover live sessions, community events and meetups shared on ANVYA.</p></div>{loading?<Loader2 className="mx-auto animate-spin"/>:!events.length?<Card><CardContent className="py-16 text-center text-muted-foreground">No events published yet. Create an event from your profile.</CardContent></Card>:<div className="space-y-4">{events.map(e=>{const st=state(e);return <Card key={e.id} className="overflow-hidden rounded-3xl"><CardContent className="p-5 md:p-6"><div className="flex flex-wrap items-center gap-2">{st==="live"&&<Badge className="bg-red-600 text-white"><Radio className="mr-1 size-3 animate-pulse"/>LIVE NOW</Badge>}{st==="upcoming"&&<Badge variant="outline">Upcoming</Badge>}{st==="ended"&&<Badge variant="outline">Ended</Badge>}<Badge>{e.subject||"Event"}</Badge></div><h2 className="mt-3 text-2xl font-black">{e.title}</h2><div className="mt-3 grid gap-2 text-sm text-muted-foreground sm:grid-cols-2"><span className="inline-flex items-center gap-2"><CalendarDays className="size-4"/> {e.event_start?new Date(e.event_start).toLocaleString():"Date TBA"}</span>{e.event_location&&<span className="inline-flex items-center gap-2"><MapPin className="size-4"/>{e.event_location}</span>}</div>{e.image_url&&<img src={e.image_url} alt={e.title} className="mt-4 max-h-80 w-full rounded-2xl object-cover"/>}<div className="mt-4 whitespace-pre-wrap text-sm leading-7 text-muted-foreground" dangerouslySetInnerHTML={{__html:e.content}}/><div className="mt-5 flex flex-wrap gap-2 border-t pt-4"><Button variant={rsvps[e.id]==="going"?"default":"outline"} onClick={()=>rsvp(e,"going")} disabled={!me}>I'm Going</Button><Button variant={rsvps[e.id]==="interested"?"default":"outline"} onClick={()=>rsvp(e,"interested")} disabled={!me}>Interested</Button>{e.event_url&&<a href={e.event_url} target="_blank" rel="noreferrer"><Button variant="outline"><ExternalLink className="mr-2 size-4"/>Join / Event Link</Button></a>}</div></CardContent></Card>})}</div>}</div></div>;
}