import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { BarChart3, Eye, Heart, MessageCircle, Repeat2, Users, Loader2 } from "lucide-react";
export default function IdeasAnalytics(){
 const [loading,setLoading]=useState(true),[data,setData]=useState<any>(null);
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return}const {data:p}=await supabase.from("idea_profiles").select("display_name,followers_count,following_count").eq("user_id",user.id).maybeSingle();const {data:posts}=await supabase.from("idea_posts").select("id,title,created_at,status").eq("user_id",user.id).order("created_at",{ascending:false}).limit(100);const ids=(posts||[]).map(x=>x.id);let likes=0,comments=0,shares=0;if(ids.length){const [r,c,s]=await Promise.all([supabase.from("idea_post_reactions").select("reaction").in("post_id",ids),supabase.from("idea_post_comments").select("id").in("post_id",ids),supabase.from("idea_post_reshares").select("user_id").in("post_id",ids)]);likes=(r.data||[]).filter(x=>x.reaction==="like").length;comments=(c.data||[]).length;shares=(s.data||[]).length}setData({profile:p,posts:posts||[],likes,comments,shares});setLoading(false)})()},[]);
 if(loading)return <div className="min-h-screen grid place-items-center"><Loader2 className="animate-spin"/></div>;
 if(!data)return <div className="p-8 text-center text-muted-foreground">Sign in with Gmail to view your analytics.</div>;
 const stats=[["Posts",data.posts.length,BarChart3],["Likes",data.likes,Heart],["Comments",data.comments,MessageCircle],["Reshares",data.shares,Repeat2],["Followers",data.profile?.followers_count||0,Users]];
 return <div className="min-h-screen bg-[#f8f9fc] dark:bg-background"><div className="mx-auto max-w-6xl px-4 py-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">Creator Analytics</p><h1 className="mt-1 text-3xl font-black">Your ANVYA performance</h1><p className="mt-2 text-sm text-muted-foreground">A simple professional dashboard inspired by creator analytics on social platforms.</p></div><Badge variant="outline">Last 100 posts</Badge></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{stats.map(([label,value,Icon]:any)=><Card key={label} className="rounded-2xl"><CardContent className="p-5"><Icon className="size-5 text-primary"/><p className="mt-4 text-3xl font-black">{value}</p><p className="text-xs text-muted-foreground">{label}</p></CardContent></Card>)}</div><Card className="mt-5 rounded-3xl"><CardContent className="p-6"><h2 className="text-xl font-black">Content performance</h2><div className="mt-4 space-y-3">{data.posts.slice(0,8).map((p:any)=><div key={p.id} className="flex items-center justify-between gap-4 rounded-2xl border p-4"><div className="min-w-0"><p className="truncate font-semibold">{p.title}</p><p className="text-xs text-muted-foreground">{new Date(p.created_at).toLocaleDateString()}</p></div><Badge variant="outline">{p.status}</Badge></div>)}{!data.posts.length&&<p className="text-sm text-muted-foreground">Publish your first post to start seeing analytics.</p>}</div></CardContent></Card></div></div>;
}