import {useEffect,useState} from "react";
import {supabase} from "@/integrations/supabase/client";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {Card,CardContent} from "@/components/ui/card";
import {Badge} from "@/components/ui/badge";
import {toast} from "sonner";
import {Users,Plus,Globe2,LogIn,Search,Sparkles,ArrowLeft} from "lucide-react";

export default function IdeasCommunities(){
 const [user,setUser]=useState<any>(null),[items,setItems]=useState<any[]>([]),[open,setOpen]=useState(false),[name,setName]=useState(""),[description,setDescription]=useState(""),[q,setQ]=useState("");
 const load=async()=>{const {data:{user}}=await supabase.auth.getUser();setUser(user);const {data}=await supabase.from("idea_communities").select("*").eq("visibility","public").order("created_at",{ascending:false});setItems(data||[])};
 useEffect(()=>{load()},[]); const filtered=items.filter(c=>!q||[c.name,c.description,c.slug].filter(Boolean).join(" ").toLowerCase().includes(q.toLowerCase()));
 const create=async()=>{if(!user)return toast.error("Please sign in first.");const slug=name.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")+"-"+Math.random().toString(36).slice(2,7);const {data,error}=await supabase.from("idea_communities").insert({owner_id:user.id,name:name.trim(),description:description.trim(),slug,visibility:"public"}).select().single();if(error)toast.error(error.message);else{await supabase.from("idea_community_members").insert({community_id:data.id,user_id:user.id,role:"owner"});toast.success("Community created.");setName("");setDescription("");setOpen(false);load()}};
 const join=async(id:string)=>{if(!user)return toast.error("Please sign in first.");const {error}=await supabase.from("idea_community_members").insert({community_id:id,user_id:user.id,role:"member"});if(error)toast.error(error.message);else toast.success("Joined community.")};
 return <div className="min-h-screen bg-gradient-to-b from-background via-background to-primary/5"><div className="container mx-auto max-w-6xl px-4 py-8 md:py-12"><Button variant="ghost" size="sm" className="mb-5" onClick={()=>location.href="/anvya"}><ArrowLeft className="mr-2 size-4"/>Back to Ideas</Button><div className="mb-7 rounded-[28px] border bg-card p-6 md:p-8"><div className="mb-6 flex flex-wrap items-center justify-between gap-4"><div className="flex items-start gap-3"><span className="rounded-2xl bg-primary/10 p-3 text-primary"><Globe2/></span><div><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">ANVYA Network</p><h1 className="text-3xl font-black">🌍 Ideas Communities</h1><p className="mt-1 text-muted-foreground">Find your people, start a community and build conversations around what you care about.</p></div></div><Button onClick={()=>user?setOpen(!open):toast.error("Please sign in first.")}>{user?<><Plus className="mr-2 size-4"/>Create Community</>:<><LogIn className="mr-2 size-4"/>Sign in</>}</Button></div>
 <div className="grid gap-3 md:grid-cols-[1fr_auto]"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-muted-foreground"/><Input className="pl-9 rounded-xl" placeholder="Search communities..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="rounded-xl border px-4 py-2 text-sm text-muted-foreground">{items.length} public communities</div></div></div>{open&&<Card className="mb-6"><CardContent className="grid gap-4 p-6"><div className="flex items-center gap-2 font-bold"><Sparkles className="size-4 text-primary"/>Create your community</div><Input placeholder="Community name" value={name} onChange={e=>setName(e.target.value)}/><Textarea placeholder="What is this community about?" value={description} onChange={e=>setDescription(e.target.value)}/><Button onClick={create} disabled={!name.trim()}>Create Public Community</Button></CardContent></Card>}
 <div className="grid gap-4 md:grid-cols-2">{filtered.map(c=><Card key={c.id}><CardContent className="p-6"><div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-bold">{c.name}</h2><p className="mt-2 text-sm text-muted-foreground">{c.description||"Community for ideas and discussion."}</p></div><Badge><Globe2 className="mr-1 size-3"/>Public</Badge></div><div className="mt-5 flex justify-between"><span className="text-xs text-muted-foreground">/{c.slug}</span><Button size="sm" variant="outline" onClick={()=>join(c.id)}><Users className="mr-2 size-4"/>Join</Button></div></CardContent></Card>)}</div>
 {!filtered.length&&<Card><CardContent className="p-10 text-center text-muted-foreground">No matching communities yet. Create the first public community and invite others.</CardContent></Card>}</div></div>
}