import {useEffect,useRef,useState} from "react";
import {useNavigate,useParams} from "react-router-dom";
import {supabase} from "@/integrations/supabase/client";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {Card,CardContent} from "@/components/ui/card";
import {Badge} from "@/components/ui/badge";
import {toast} from "sonner";
import {ArrowLeft,UserPlus,UserCheck,Users,FileText,Activity,HelpCircle,Save,ExternalLink,Loader2,UserCircle2,Camera,UserRoundPlus,ShieldCheck,Upload,Clock3} from "lucide-react";

type Profile={user_id:string;display_name:string;first_name?:string|null;middle_name?:string|null;last_name?:string|null;state?:string|null;country?:string|null;bio:string|null;avatar_url:string|null;cover_url:string|null;location:string|null;website_url:string|null;linkedin_url:string|null;github_url:string|null;instagram_url:string|null;twitter_url:string|null;public_id?:string|null;reputation_points?:number;level?:number;verified?:boolean};
type Post={id:string;user_id:string;display_name:string|null;profile_image_url:string|null;title:string;content:string;post_type:string;visibility:string;subject:string;image_url:string|null;created_at:string;status:string};

export default function IdeasProfile(){
 const {userId}=useParams(); const nav=useNavigate();
 const [me,setMe]=useState<string|null>(null),[p,setP]=useState<Profile|null>(null),[verification,setVerification]=useState<any>(null),[posts,setPosts]=useState<Post[]>([]),[tab,setTab]=useState("posts"),[reshares,setReshares]=useState<Post[]>([]),[following,setFollowing]=useState(false),[friendStatus,setFriendStatus]=useState<string|null>(null),[edit,setEdit]=useState(false),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[form,setForm]=useState<Partial<Profile>>({}),[avatarFile,setAvatarFile]=useState<File|null>(null),[coverFile,setCoverFile]=useState<File|null>(null),[requesters,setRequesters]=useState<Profile[]>([]);
 const load=async()=>{setLoading(true);const {data:{user}}=await supabase.auth.getUser();setMe(user?.id||null);const id=!userId||userId==="me"?user?.id:userId;if(!id){setLoading(false);nav("/ideas/account",{replace:true});return}
 let {data:profile}=await supabase.from("idea_profiles").select("*").eq("user_id",id).maybeSingle();
 if(!profile&&user?.id===id){const fallback={user_id:id,display_name:user.user_metadata?.full_name||user.email?.split("@")[0]||"Member"};await supabase.from("idea_profiles").upsert(fallback);profile=fallback as any}
 setP(profile as Profile|null);setForm(profile||{}); if(user&&id===user.id){const {data:v}=await supabase.from("idea_verification_requests").select("id,status,rejection_reason,created_at").eq("user_id",id).maybeSingle();setVerification(v||null);} if(profile?.user_id===id && !profile.public_id){await supabase.from("idea_profiles").update({public_id:"CST-"+id.replace(/-/g,"").slice(0,10).toUpperCase()}).eq("user_id",id); profile.public_id="CST-"+id.replace(/-/g,"").slice(0,10).toUpperCase();}
 const {data:ps}=await supabase.from("idea_posts").select("*").eq("user_id",id).eq("status","approved").order("created_at",{ascending:false});setPosts((ps as Post[])||[]);
 const {data:shareRows}=await supabase.from("idea_post_reshares").select("post_id").eq("user_id",id).order("created_at",{ascending:false});
 const shareIds=(shareRows||[]).map(x=>x.post_id);
 if(shareIds.length){const {data:rp}=await supabase.from("idea_posts").select("*").in("id",shareIds).eq("status","approved"); const ordered=shareIds.map(sid=>(rp||[]).find(x=>x.id===sid)).filter(Boolean) as Post[]; setReshares(ordered);} else setReshares([]);
 if(user&&id===user.id){const {data:incoming}=await supabase.from("idea_friendships").select("requester_id").eq("addressee_id",user.id).eq("status","pending");const ids=(incoming||[]).map(x=>x.requester_id);if(ids.length){const {data:rp}=await supabase.from("idea_profiles").select("*").in("user_id",ids);setRequesters((rp as Profile[])||[])}}
 if(user&&id!==user.id){const f=await supabase.from("idea_follows").select("follower_id").eq("follower_id",user.id).eq("following_id",id).maybeSingle();setFollowing(!!f.data);
 const fr=await supabase.from("idea_friendships").select("requester_id,addressee_id,status").or("and(requester_id.eq."+user.id+",addressee_id.eq."+id+"),and(requester_id.eq."+id+",addressee_id.eq."+user.id+")").maybeSingle();setFriendStatus(fr.data?.status||null)}
 setLoading(false)};
 useEffect(()=>{load()},[userId]);
 const toggleFollow=async()=>{if(!me||!p)return toast.error("Please sign in first.");if(following){const {error}=await supabase.from("idea_follows").delete().eq("follower_id",me).eq("following_id",p.user_id);if(error)toast.error(error.message);else{setFollowing(false);toast.success("Unfollowed.")}}else{const {error}=await supabase.from("idea_follows").insert({follower_id:me,following_id:p.user_id});if(error)toast.error(error.message);else{setFollowing(true);toast.success("Following.")}}};
 const respondFriend=async(requester:string,status:"accepted"|"rejected")=>{if(!me)return;const {error}=await supabase.from("idea_friendships").update({status,updated_at:new Date().toISOString()}).eq("requester_id",requester).eq("addressee_id",me);if(error)toast.error(error.message);else{setRequesters(x=>x.filter(y=>y.user_id!==requester));toast.success(status==="accepted"?"Friend request accepted.":"Friend request rejected.");}};
 const friend=async()=>{if(!me||!p)return toast.error("Please sign in first.");if(friendStatus==="accepted"||friendStatus==="pending")return;const {error}=await supabase.from("idea_friendships").insert({requester_id:me,addressee_id:p.user_id});if(error)toast.error(error.message);else{setFriendStatus("pending");toast.success("Friend request sent.")}};
 const uploadImage=async(file:File,kind:"avatar"|"cover")=>{if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>5*1024*1024)throw new Error("Use JPG, PNG or WEBP up to 5 MB.");const ext=file.name.split(".").pop()||"jpg";const path=me+"/"+kind+"-"+crypto.randomUUID()+"."+ext;const up=await supabase.storage.from("idea-images").upload(path,file,{contentType:file.type,upsert:false});if(up.error)throw up.error;return supabase.storage.from("idea-images").getPublicUrl(path).data.publicUrl};
 const save=async()=>{if(!me)return;setSaving(true);try{let avatar=form.avatar_url,cover=form.cover_url;if(avatarFile)avatar=await uploadImage(avatarFile,"avatar");if(coverFile)cover=await uploadImage(coverFile,"cover");const payload={...form,user_id:me,display_name:[form.first_name,form.middle_name,form.last_name].filter(Boolean).join(" ").trim()||String(form.display_name||"").trim()||"Member",updated_at:new Date().toISOString()};const {data,error}=await supabase.from("idea_profiles").upsert({...payload,avatar_url:avatar,cover_url:cover}).select().single();if(error)toast.error(error.message);else{setP(data);setForm(data);setEdit(false);setAvatarFile(null);setCoverFile(null);toast.success("Profile updated.")}}catch(e:any){toast.error(e?.message||"Could not update profile")}setSaving(false)};
 const social=[["Website",p?.website_url],["LinkedIn",p?.linkedin_url],["GitHub",p?.github_url],["Instagram",p?.instagram_url],["X",p?.twitter_url]].filter(x=>x[1]);
 if(loading)return <div className="min-h-screen flex items-center justify-center"><Loader2 className="animate-spin"/></div>;
 if(!p)return <div className="container mx-auto max-w-3xl px-4 py-12"><Card><CardContent className="p-10 text-center">Profile not found.</CardContent></Card></div>;
 return (
  <div className="min-h-screen bg-background">
   <div className="container mx-auto max-w-5xl px-4 py-6 md:py-10">
    <Button variant="ghost" onClick={()=>nav("/ideas")}><ArrowLeft className="mr-2 size-4"/>Ideas</Button>
    <Card className="mt-4 overflow-hidden rounded-[28px]">
     <div className="relative h-44 bg-gradient-to-r from-blue-600/80 via-violet-600/80 to-fuchsia-600/70">{p.cover_url&&<img src={p.cover_url} className="size-full object-cover" alt="Cover"/>}{me===p.user_id&&edit&&<label className="absolute right-4 top-4 cursor-pointer rounded-xl bg-black/60 px-3 py-2 text-sm text-white"><Camera className="mr-2 inline size-4"/>Change Cover<input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>setCoverFile(e.target.files?.[0]||null)}/></label>}</div>
     <CardContent className="relative p-6">
      <div className="-mt-20 flex flex-col gap-4 md:flex-row md:items-end">
       <div className="relative size-28 overflow-hidden rounded-3xl border-4 border-background bg-muted">
        {p.avatar_url?<img src={p.avatar_url} className="size-full object-cover" alt={p.display_name}/>:<UserCircle2 className="size-full p-5 text-muted-foreground"/>}
        {me===p.user_id&&edit&&<label className="absolute inset-x-0 bottom-0 cursor-pointer bg-black/60 py-2 text-center text-xs text-white">Change<input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>setAvatarFile(e.target.files?.[0]||null)}/></label>}
       </div>
       <div className="flex-1"><h1 className="text-3xl font-black">{p.display_name}</h1><p className="text-sm text-muted-foreground">{[p.state,p.country].filter(Boolean).join(", ")||p.location||"Ideas Community member"}</p><div className="mt-2 flex flex-wrap gap-2"><Badge variant="secondary">🌍 Public ID: {p.public_id||"CST-"+p.user_id.replace(/-/g,"").slice(0,10).toUpperCase()}</Badge>{p.verified&&<Badge className="bg-blue-600 text-white">✓ Verified</Badge>}<Badge>⭐ Level {p.level||1}</Badge><Badge variant="outline">🏆 {p.reputation_points||0} Points</Badge></div></div>
       {me===p.user_id?<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>nav("/ideas/account")}>Account</Button><Button onClick={()=>setEdit(!edit)}>{edit?"Cancel":"Edit Profile"}</Button></div>:<div className="flex flex-wrap gap-2"><Button onClick={toggleFollow} variant={following?"outline":"default"}>{following?<UserCheck className="mr-2 size-4"/>:<UserPlus className="mr-2 size-4"/>}{following?"Unfollow":"Follow"}</Button><Button variant="outline" onClick={friend} disabled={friendStatus==="accepted"||friendStatus==="pending"}>{friendStatus==="accepted"?<UserCheck className="mr-2 size-4"/>:<Users className="mr-2 size-4"/>}{friendStatus==="accepted"?"Friends":friendStatus==="pending"?"Request Sent":"Add Friend"}</Button></div>}
      </div>
      {p.bio&&<p className="mt-4 text-muted-foreground">{p.bio}</p>}
      {social.length>0&&<div className="mt-4 flex flex-wrap gap-2">{social.map(([n,u])=><a key={n} href={String(u)} target="_blank" rel="noreferrer"><Badge variant="secondary" className="gap-1"><ExternalLink size={12}/>{n}</Badge></a>)}</div>}
      {edit&&me===p.user_id&&<div className="mt-6 grid gap-4 rounded-2xl border bg-muted/20 p-5 md:grid-cols-2"><Input placeholder="First Name" value={String(form.first_name||"")} onChange={e=>setForm({...form,first_name:e.target.value})}/><Input placeholder="Middle Name" value={String(form.middle_name||"")} onChange={e=>setForm({...form,middle_name:e.target.value})}/><Input placeholder="Last Name" value={String(form.last_name||"")} onChange={e=>setForm({...form,last_name:e.target.value})}/><Input placeholder="State" value={String(form.state||"")} onChange={e=>setForm({...form,state:e.target.value})}/><Input placeholder="Country" value={String(form.country||"")} onChange={e=>setForm({...form,country:e.target.value})}/><Input placeholder="Name" value={String(form.display_name||"")} onChange={e=>setForm({...form,display_name:e.target.value})}/><Input placeholder="Location" value={String(form.location||"")} onChange={e=>setForm({...form,location:e.target.value})}/><Textarea className="md:col-span-2" placeholder="Bio" value={String(form.bio||"")} onChange={e=>setForm({...form,bio:e.target.value})}/>{[["website_url","Website"],["linkedin_url","LinkedIn"],["github_url","GitHub"],["instagram_url","Instagram"],["twitter_url","X"]].map(([k,label])=><Input key={k} placeholder={label+" URL"} value={String((form as any)[k]||"")} onChange={e=>setForm({...form,[k]:e.target.value})}/>) }<div className="md:col-span-2 rounded-xl border border-dashed p-3 text-sm text-muted-foreground"><Camera className="mr-2 inline size-4"/>Use the Change button on the cover/avatar to upload images. JPG, PNG or WEBP, max 5 MB.</div><Button className="md:col-span-2" onClick={save} disabled={saving}>{saving?<Loader2 className="mr-2 size-4 animate-spin"/>:<Save className="mr-2 size-4"/>}Save Profile</Button></div>}
     </CardContent>
    </Card>
    {me===p.user_id&&requesters.length>0&&<Card className="mt-5"><CardContent className="p-6"><h3 className="mb-4 text-lg font-bold">Friend Requests</h3>{requesters.map(r=><div key={r.user_id} className="flex items-center gap-3 border-b py-3"><div className="size-10 overflow-hidden rounded-full bg-muted">{r.avatar_url?<img src={r.avatar_url} className="size-full object-cover" alt={r.display_name}/>:<UserCircle2 className="size-full p-2"/>}</div><div className="flex-1"><p className="font-bold">{r.display_name}</p><p className="text-xs text-muted-foreground">{r.location||"Ideas Community"}</p></div><Button size="sm" onClick={()=>respondFriend(r.user_id,"accepted")}><UserCheck className="mr-1 size-4"/>Accept</Button><Button size="sm" variant="outline" onClick={()=>respondFriend(r.user_id,"rejected")}>Reject</Button></div>)}</CardContent></Card>}
    {me===p.user_id&&<VerificationCard profile={p} request={verification} onSubmitted={v=>setVerification(v)}/>}
    <ProfileProgress userId={p.user_id} posts={posts.length} level={p.level||1} points={p.reputation_points||0}/><div className="mt-6 flex flex-wrap gap-2">{[["posts","Posts",FileText],["reshares","Reshares",Activity],["activity","Activity",Activity],["friends","Friends",Users],["followers","Followers",Users],["following","Following",UserPlus],["questions","Questions",HelpCircle]].map(([k,n,I]:any)=><Button key={k} variant={tab===k?"default":"outline"} onClick={()=>setTab(k)}><I className="mr-2 size-4"/>{n}</Button>)}</div>
    <div className="mt-5 space-y-4">
     {tab==="posts"&&posts.filter(x=>x.post_type==="post").map(x=><PostCard key={x.id} x={x}/>)}
     {tab==="reshares"&&reshares.map(x=><PostCard key={x.id} x={x} resharedByProfile/>)}
     {tab==="questions"&&posts.filter(x=>x.post_type==="question").map(x=><PostCard key={x.id} x={x}/>)}
     {tab==="activity"&&<Card><CardContent className="space-y-4 p-6">{posts.slice(0,20).map(x=><div key={x.id} className="flex gap-3 border-b pb-3"><Activity className="mt-1 size-4 text-primary"/><div><b>{x.post_type==="question"?"Asked a question":"Published a post"}</b><p className="text-sm text-muted-foreground">{x.title} • {new Date(x.created_at).toLocaleDateString()}</p></div></div>)}</CardContent></Card>}
     {(tab==="friends"||tab==="following"||tab==="followers")&&<RelationshipList userId={p.user_id} mode={tab as "friends"|"following"|"followers"}/>}
    </div>
   </div>
  </div>
 );
}

function PostCard({x,resharedByProfile=false}:{x:Post;resharedByProfile?:boolean}){
 const [me,setMe]=useState<string|null>(null),[reaction,setReaction]=useState<string|null>(null),[likes,setLikes]=useState(0),[dislikes,setDislikes]=useState(0),[comments,setComments]=useState<any[]>([]),[text,setText]=useState(""),[reshared,setReshared]=useState(false);
 const load=async()=>{const {data:{user}}=await supabase.auth.getUser();setMe(user?.id||null);const [r,c,s]=await Promise.all([supabase.from("idea_post_reactions").select("user_id,reaction").eq("post_id",x.id),supabase.from("idea_post_comments").select("*").eq("post_id",x.id).order("created_at",{ascending:true}),supabase.from("idea_post_reshares").select("user_id").eq("post_id",x.id)]);const rs=r.data||[];setLikes(rs.filter(v=>v.reaction==="like").length);setDislikes(rs.filter(v=>v.reaction==="dislike").length);setReaction(user?.id?rs.find(v=>v.user_id===user.id)?.reaction||null:null);setComments(c.data||[]);setReshared(!!user?.id&&(s.data||[]).some(v=>v.user_id===user.id))};
 useEffect(()=>{load()},[x.id]);
 const react=async(kind:"like"|"dislike")=>{if(!me)return toast.error("Please sign in first.");if(reaction===kind){const {error}=await supabase.from("idea_post_reactions").delete().eq("post_id",x.id).eq("user_id",me);if(error)toast.error(error.message);else{setReaction(null);kind==="like"?setLikes(v=>Math.max(0,v-1)):setDislikes(v=>Math.max(0,v-1))}}else{if(reaction){await supabase.from("idea_post_reactions").delete().eq("post_id",x.id).eq("user_id",me)}const {error}=await supabase.from("idea_post_reactions").insert({post_id:x.id,user_id:me,reaction:kind});if(error)toast.error(error.message);else{if(reaction==="like")setLikes(v=>Math.max(0,v-1));if(reaction==="dislike")setDislikes(v=>Math.max(0,v-1));kind==="like"?setLikes(v=>v+1):setDislikes(v=>v+1);setReaction(kind)}}};
 const comment=async()=>{if(!me)return toast.error("Please sign in first.");if(!text.trim())return;const {data,error}=await supabase.from("idea_post_comments").insert({post_id:x.id,user_id:me,content:text.trim()}).select().single();if(error)toast.error(error.message);else{setComments(v=>[...v,data]);setText("")}};
 const reshare=async()=>{if(!me)return toast.error("Please sign in first.");if(reshared){const {error}=await supabase.from("idea_post_reshares").delete().eq("post_id",x.id).eq("user_id",me);if(error)toast.error(error.message);else setReshared(false)}else{const {error}=await supabase.from("idea_post_reshares").insert({post_id:x.id,user_id:me});if(error)toast.error(error.message);else setReshared(true)}};
 return <Card><CardContent className="p-5">{resharedByProfile&&<div className="mb-3 text-sm font-semibold text-primary">🔁 Reshared by this profile</div>}<div className="mb-2 flex gap-2"><Badge>{x.post_type==="question"?"Question":x.subject}</Badge><Badge variant="outline">{x.visibility==="friends"?"👥 Friends Only":"🌍 Public"}</Badge></div><h2 className="text-xl font-bold">{x.title}</h2><p className="mt-2 whitespace-pre-wrap text-muted-foreground">{x.content}</p>{x.image_url&&<img src={x.image_url} className="mt-4 max-h-96 rounded-2xl object-cover" alt={x.title}/>}<div className="mt-5 flex flex-wrap gap-2 border-y py-3"><Button size="sm" variant={reaction==="like"?"default":"outline"} onClick={()=>react("like")}>👍 Like {likes}</Button><Button size="sm" variant={reaction==="dislike"?"default":"outline"} onClick={()=>react("dislike")}>👎 Dislike {dislikes}</Button><Button size="sm" variant={reshared?"default":"outline"} onClick={reshare}>🔁 {reshared?"Reshared":"Reshare"}</Button></div><div className="mt-4"><div className="flex gap-2"><Input value={text} onChange={e=>setText(e.target.value)} placeholder="Write a comment..." maxLength={2000}/><Button onClick={comment}>Comment</Button></div><div className="mt-3 space-y-2">{comments.map(c=><div key={c.id} className="rounded-xl bg-muted/50 p-3 text-sm"><p>{c.content}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(c.created_at).toLocaleString()}</p></div>)}</div></div></CardContent></Card>;
}

function RelationshipList({userId,mode}:{userId:string;mode:"friends"|"following"|"followers"}){
 const [items,setItems]=useState<any[]>([]);
 useEffect(()=>{(async()=>{let ids:string[]=[];if(mode==="following"){const {data}=await supabase.from("idea_follows").select("following_id").eq("follower_id",userId);ids=(data||[]).map(x=>x.following_id)}else if(mode==="followers"){const {data}=await supabase.from("idea_follows").select("follower_id").eq("following_id",userId);ids=(data||[]).map(x=>x.follower_id)}else{const {data}=await supabase.from("idea_friendships").select("requester_id,addressee_id").eq("status","accepted").or("requester_id.eq."+userId+",addressee_id.eq."+userId);ids=(data||[]).map(x=>x.requester_id===userId?x.addressee_id:x.requester_id)}if(ids.length){const {data}=await supabase.from("idea_profiles").select("*").in("user_id",ids);setItems(data||[])}else setItems([])})()},[userId,mode]);
 return <Card><CardContent className="p-6">{items.length===0?<p className="text-muted-foreground">No {mode} yet.</p>:items.map(x=><button key={x.user_id} onClick={()=>location.href="/ideas/profile/"+x.user_id} className="flex w-full items-center gap-3 border-b py-3 text-left hover:bg-muted/40"><div className="size-10 overflow-hidden rounded-full bg-muted">{x.avatar_url?<img src={x.avatar_url} className="size-full object-cover" alt={x.display_name}/>:<UserCircle2 className="size-full p-2"/>}</div><div><p className="font-bold">{x.display_name}</p><p className="text-xs text-muted-foreground">{x.location||"Ideas Community"}</p></div></button>)}</CardContent></Card>;
}


function ProfileProgress({userId,posts,level,points}:{userId:string;posts:number;level:number;points:number}){
 const [badges,setBadges]=useState<any[]>([]),[achievements,setAchievements]=useState<any[]>([]),[communities,setCommunities]=useState<any[]>([]);
 useEffect(()=>{(async()=>{const b=await supabase.from("idea_badges").select("*").eq("user_id",userId).order("created_at",{ascending:false});setBadges(b.data||[]);const a=await supabase.from("idea_post_achievements").select("*").eq("user_id",userId).order("created_at",{ascending:false}).limit(50);setAchievements(a.data||[]);const c=await supabase.from("idea_community_members").select("community_id,role").eq("user_id",userId);const ids=(c.data||[]).map(x=>x.community_id);if(ids.length){const q=await supabase.from("idea_communities").select("id,name,slug,visibility").in("id",ids);setCommunities((q.data||[]).map(x=>({...x,role:(c.data||[]).find(m=>m.community_id===x.id)?.role})))}})()},[userId]);
 return <div className="mt-5 grid gap-4 md:grid-cols-3">
  <Card><CardContent className="p-5"><p className="text-xs uppercase text-muted-foreground">Community Level</p><p className="mt-1 text-2xl font-black">Level {level}</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary" style={{width:Math.min(100,((points%100)/100)*100)+"%"}}/></div><p className="mt-2 text-xs text-muted-foreground">{points} reputation points • keep contributing to unlock stages</p></CardContent></Card>
  <Card><CardContent className="p-5"><p className="text-xs uppercase text-muted-foreground">Badges & Leadership</p><div className="mt-3 flex flex-wrap gap-2">{badges.length?badges.map(b=><Badge key={b.id}>🏅 {b.badge_name}</Badge>):<Badge variant="outline">🌱 Community Starter</Badge>}</div><p className="mt-3 text-xs text-muted-foreground">Stages: Starter → Contributor → Leader → Community Builder</p><div className="mt-4 rounded-xl border bg-muted/20 p-3"><p className="text-xs font-bold uppercase text-muted-foreground">Post Achievements</p>{achievements.length?<div className="mt-2 space-y-2">{achievements.slice(0,8).map(a=><div key={a.id} className="flex items-center justify-between rounded-lg border bg-background p-2"><span className="text-sm">🏅 {a.achievement_name}</span><Badge variant="outline">+{a.points_awarded} pts</Badge></div>)}</div>:<p className="mt-2 text-xs text-muted-foreground">Publish approved posts to earn achievements and points.</p>}</div></CardContent></Card>
  <Card><CardContent className="p-5"><p className="text-xs uppercase text-muted-foreground">Communities</p>{communities.length?<div className="mt-2 space-y-2">{communities.slice(0,4).map(c=><div key={c.id} className="flex items-center justify-between rounded-lg border p-2"><span className="font-medium">{c.name}</span><Badge variant="outline">{c.role}</Badge></div>)}</div>:<p className="mt-3 text-sm text-muted-foreground">No communities joined yet.</p>}<Button size="sm" className="mt-3" onClick={()=>location.href="/ideas/communities"}><Users className="mr-2 size-4"/>Explore Communities</Button></CardContent></Card>
 </div>;
}

function VerificationCard({profile,request,onSubmitted}:{profile:Profile;request:any;onSubmitted:(v:any)=>void}){
 const [file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[cameraOpen,setCameraOpen]=useState(false),[cameraError,setCameraError]=useState(""),[stream,setStream]=useState<MediaStream|null>(null);
 const videoRef=useRef<HTMLVideoElement|null>(null);
 useEffect(()=>()=>{stream?.getTracks().forEach(t=>t.stop())},[stream]);
 const openCamera=async()=>{setCameraError("");try{if(!navigator.mediaDevices?.getUserMedia)throw new Error("Camera is not supported in this browser.");const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user"},audio:false});setStream(s);setCameraOpen(true);setTimeout(()=>{if(videoRef.current){videoRef.current.srcObject=s;videoRef.current.play().catch(()=>{})}},50)}catch(e:any){setCameraError(e?.message||"Camera permission was denied.")}};
 const closeCamera=()=>{stream?.getTracks().forEach(t=>t.stop());setStream(null);setCameraOpen(false)};
 const capture=async()=>{const video=videoRef.current;if(!video||!video.videoWidth)return toast.error("Camera is not ready yet.");const canvas=document.createElement("canvas");canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext("2d")?.drawImage(video,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>{if(blob){setFile(new File([blob],"selfie-camera.jpg",{type:"image/jpeg"}));closeCamera();toast.success("Selfie captured. You can submit it now.")}else toast.error("Could not capture selfie.")},"image/jpeg",0.92)};
 const submit=async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return toast.error("Please sign in first.");if(!file)return toast.error("Take or upload a clear selfie first.");if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>5*1024*1024)return toast.error("Use JPG, PNG or WEBP up to 5 MB.");setBusy(true);try{const path=user.id+"/selfie-"+crypto.randomUUID()+"."+((file.name.split(".").pop()||"jpg").toLowerCase());const up=await supabase.storage.from("idea-verification").upload(path,file,{contentType:file.type,upsert:false});if(up.error)throw up.error;const {data,error}=await supabase.from("idea_verification_requests").upsert({user_id:user.id,selfie_path:path,status:"pending",rejection_reason:null,reviewed_by:null,reviewed_at:null},{onConflict:"user_id"}).select("id,status,rejection_reason,created_at").single();if(error)throw error;await supabase.from("idea_profiles").update({verification_status:"pending"}).eq("user_id",user.id);onSubmitted(data);setFile(null);toast.success("Verification request submitted.");}catch(e:any){toast.error(e?.message||"Verification request failed.");}finally{setBusy(false)}};
 const status=request?.status||"not_submitted";
 return <Card className="mt-5 overflow-hidden border-primary/20"><CardContent className="p-5"><div className="flex items-start gap-3"><div className="rounded-2xl bg-primary/10 p-3"><ShieldCheck className="text-primary"/></div><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-black text-lg">Profile Verification</h3><Badge variant={status==="verified"?"default":"outline"}>{status==="verified"?"✓ Verified":status==="pending"?"Pending Review":status==="rejected"?"Rejected":"Not Submitted"}</Badge></div><p className="mt-1 text-sm text-muted-foreground">Submit one clear selfie for manual review. Your selfie is stored privately and is not shown publicly.</p>{status==="rejected"&&request?.rejection_reason&&<p className="mt-2 text-sm text-destructive">Reason: {request.rejection_reason}</p>}{status!=="verified"&&<div className="mt-4 space-y-3"><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><label className="flex flex-1 cursor-pointer items-center gap-2 rounded-xl border border-dashed p-3 text-sm"><Upload size={16}/><span className="truncate">{file?.name||"Choose selfie from device"}</span><input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><Button type="button" variant="outline" onClick={openCamera} disabled={busy||status==="pending"}><Camera className="mr-2 size-4"/>Open Camera</Button><Button onClick={submit} disabled={busy||status==="pending"||!file}>{busy?<Loader2 className="mr-2 size-4 animate-spin"/>:<ShieldCheck className="mr-2 size-4"/>}{status==="pending"?"Under Review":"Submit for Verification"}</Button></div>{cameraError&&<p className="text-sm text-destructive">{cameraError}</p>}{cameraOpen&&<div className="rounded-2xl border bg-black/5 p-3"><video ref={videoRef} autoPlay playsInline muted className="mx-auto aspect-video w-full max-w-md rounded-xl bg-black object-cover"/><div className="mt-3 flex justify-center gap-2"><Button type="button" onClick={capture}><Camera className="mr-2 size-4"/>Capture Selfie</Button><Button type="button" variant="outline" onClick={closeCamera}>Cancel</Button></div></div>}{file&&<p className="text-xs text-muted-foreground">Selected selfie: {file.name} • max 5 MB</p>}</div>}{status==="pending"&&<p className="mt-3 flex items-center gap-2 text-xs text-muted-foreground"><Clock3 size={14}/>An admin will review the selfie manually.</p>}</div></div></CardContent></Card>;
}\n