import { useEffect, useMemo, useRef, useState } from "react";
import { Helmet } from "react-helmet-async";
import { Loader2, Pause, Play, Square, Volume2, Clock, Search, RefreshCw, Zap, Radio, ExternalLink } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import WhatsAppButton from "@/components/WhatsAppButton";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Slider } from "@/components/ui/slider";
import { supabase } from "@/integrations/supabase/client";

type Article={id:string;slug:string;title:string;summary:string;content:string;category:string;topics?:string[];source:string|null;source_url:string|null;source_published_at:string|null;image_url:string|null;image_alt:string|null;reading_minutes:number|null;author:string|null;published_at:string};
const CATS=["All","AI News","Technology","SEO","AI SEO","Technical SEO","Google Updates","AI Search","ChatGPT","Gemini","AI Agents","AI Tools","Cybersecurity","AI Research","Machine Learning","Generative AI","SaaS & Startups","Digital Marketing","AI Automation"];
const LANGS=[{code:"en-US",label:"English"},{code:"hi-IN",label:"हिन्दी"},{code:"bn-IN",label:"বাংলা"},{code:"ta-IN",label:"தமிழ்"},{code:"te-IN",label:"తెలుగు"},{code:"mr-IN",label:"मराठी"},{code:"gu-IN",label:"ગુજરાતી"},{code:"pa-IN",label:"ਪੰਜਾਬੀ"},{code:"fr-FR",label:"Français"},{code:"de-DE",label:"Deutsch"},{code:"es-ES",label:"Español"},{code:"ar-SA",label:"العربية"},{code:"ja-JP",label:"日本語"},{code:"ko-KR",label:"한국어"},{code:"zh-CN",label:"中文"}];
const IMG={ai:"https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1400&q=85",tech:"https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1400&q=85",search:"https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1400&q=85",security:"https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=1400&q=85",business:"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=85"};
const imgFor=(a:Article)=>a.image_url||(/security|cyber/i.test(a.category+a.title)?IMG.security:/seo|search|google/i.test(a.category+a.title)?IMG.search:/business|saas|digital/i.test(a.category+a.title)?IMG.business:/technology|tool/i.test(a.category+a.title)?IMG.tech:IMG.ai);
const strip=(s:string)=>s.replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim();
const make=(id:string,title:string,summary:string,category:string,topics:string[],source:string,url:string,date:string,image:string,content:string):Article=>({id,slug:id,title,summary,content,category,topics,source,source_url:url,source_published_at:date,image_url:image,image_alt:title,reading_minutes:1,author:"Crazy SEO Team Editorial",published_at:date});
const FRESH:Article[]=[
make("sep13-anthropic-ai-safety","Anthropic Urges a Slower Pace of AI Development as Safety Risks Grow","Anthropic CEO Dario Amodei is calling for stronger independent evaluation and coordination as frontier AI capabilities advance.","AI News",["AI News","AI Agents","Cybersecurity","AI Research","Generative AI"],"AP","https://apnews.com/article/d59552edcb27892d8ee4d98a48397706","2026-09-13T12:00:00Z",IMG.ai,"<h2>Key update</h2><p>Anthropic CEO Dario Amodei is urging the AI industry to slow the pace of capability development while safety systems catch up. The proposal puts independent evaluation, stronger safeguards and international coordination at the center of the debate.</p><h2>What it means</h2><p>Businesses deploying AI agents should treat safety as product infrastructure. Permission boundaries, logging, sandboxing and human approval for high-impact actions are becoming increasingly important.</p><h2>SEO and AI takeaway</h2><p>Trust, transparent documentation and source-backed information matter for both traditional search and AI answer engines.</p>"),
make("sep12-openai-ipo","OpenAI Says It Will Not Go Public in 2026 Amid AI Safety Concerns","Sam Altman says OpenAI will not pursue a 2026 IPO while the company focuses on AI safety and human control.","AI News",["AI News","Technology","AI Research","AI Agents","SaaS & Startups"],"Reuters","https://www.reuters.com/legal/litigation/openai-ipo-will-not-happen-2026-amid-ai-safety-fears-altman-says-2026-09-12/","2026-09-12T12:00:00Z",IMG.ai,"<h2>Latest flash</h2><p>OpenAI CEO Sam Altman said the company will not go public in 2026, with AI safety and human control remaining major priorities. The decision comes as frontier-model companies face growing pressure to demonstrate responsible deployment.</p><h2>Business impact</h2><p>For SaaS and AI startups, the story reinforces the importance of governance, reliability, clear documentation and measurable risk controls alongside growth.</p><h2>AI SEO takeaway</h2><p>Publish authoritative product information, transparent policies and clear entity relationships so search engines and AI systems can understand the business accurately.</p>"),
make("sep12-reuters-ai-newsrooms","Reuters Expands AI-Assisted Newsroom Editing With CuttingRoom Partnership","Reuters says its new partnership will help newsrooms search, edit and publish trusted video using AI-assisted workflows.","Technology",["Technology","AI Tools","Generative AI","AI Automation","AI News"],"Reuters","https://www.reuters.com/media-center/reuters-cuttingroom-partner-provide-newsrooms-ai-assisted-video-editing-2026-09-12/","2026-09-12T08:00:00Z",IMG.tech,"<h2>Technology update</h2><p>Reuters has announced an AI-assisted video editing partnership designed to help newsrooms find, cut, caption, mix and publish verified footage through natural-language workflows.</p><h2>Why it matters</h2><p>The model shows how AI can accelerate repetitive editorial operations while keeping humans in control of the final output and newsroom rules.</p><h2>Automation takeaway</h2><p>AI automation works best when permissions, audit trails and human review are built into the workflow rather than added later.</p>"),
make("sep10-google-ai-search","Google Search Keeps Moving Toward AI Mode and Richer Answer Experiences","September search reporting points to continued AI Mode and AI Overviews changes, making technical clarity and entity-focused SEO increasingly important.","AI Search",["AI Search","SEO","AI SEO","Google Updates","Technical SEO","Gemini"],"Search Engine Land","https://searchengineland.com/library/google-seo","2026-09-10T08:00:00Z",IMG.search,"<h2>Search update</h2><p>Google Search continues to evolve around AI-assisted interfaces, including AI Mode and AI Overviews. The change means visibility is increasingly about whether a page is understood as a useful, authoritative source rather than only where a blue link ranks.</p><h2>SEO action</h2><p>Keep pages crawlable, improve internal linking, use appropriate structured data and answer important questions clearly.</p><h2>AI visibility</h2><p>Track important entities, products, services and facts across both conventional search and AI-assisted discovery.</p>"),
make("sep10-seo-visibility","September SEO Tracking Puts AI Search Visibility at the Center","Current September search monitoring highlights AI Overviews, AI Mode and new measurement layers while no confirmed ranking update was reported at the time.","SEO",["SEO","AI SEO","AI Search","Technical SEO","Business Intelligence"],"Keywords Everywhere","https://keywordseverywhere.com/news/","2026-09-10T06:00:00Z",IMG.search,"<h2>SEO update</h2><p>The September search landscape is changing quickly even when a confirmed ranking update is not rolling out. AI Overviews, AI Mode and new measurement patterns are changing how marketers evaluate visibility.</p><h2>What to measure</h2><p>Monitor organic clicks, branded demand, conversions, important page templates and AI-assisted discovery separately where possible.</p><h2>Practical action</h2><p>Strengthen topical authority, technical SEO, concise answers, original information and internal linking.</p>"),
make("sep08-google-eu-search","Google Changes European Search Results Under the EU Digital Markets Act","Google is changing parts of its European search presentation to comply with the Digital Markets Act and is warning about possible quality trade-offs.","Google Updates",["Google Updates","SEO","Technical SEO","AI Search","Digital Marketing"],"Reuters","https://www.reuters.com/world/google/google-warns-lower-quality-as-it-revamps-europe-search-results-avoid-eu-fines-2026-09-08/","2026-09-08T08:00:00Z",IMG.search,"<h2>Google update</h2><p>Google is changing parts of its European search presentation in response to the Digital Markets Act. The changes affect how some vertical and commercial search results are presented.</p><h2>SEO impact</h2><p>Marketers should monitor visibility by country instead of relying only on a global average position. Track impressions, clicks, branded demand and conversions before and after changes.</p><h2>Technical takeaway</h2><p>Maintain strong structured data, canonical signals, crawlability and clear business entities.</p>"),
make("sep08-ai-distillation","AI Model Distillation Debate Puts Model Security and Provenance in Focus","A new dispute over model distillation highlights the growing security and governance challenges around advanced AI systems.","AI Research",["AI Research","Machine Learning","Cybersecurity","Generative AI","AI News"],"Reuters","https://www.reuters.com/technology/us-accuses-chinese-ai-firms-industrial-scale-theft-ai-technology-2026-09-08/","2026-09-08T06:00:00Z",IMG.security,"<h2>Research and security</h2><p>Model distillation is a common machine-learning technique, but its use in competitive AI development has become a major policy and security issue.</p><h2>What businesses should learn</h2><p>AI companies should protect model endpoints, monitor unusual query patterns and maintain clear usage policies. Provenance and access controls become more important as model capabilities gain commercial value.</p><h2>Machine-learning takeaway</h2><p>Smaller efficient models remain useful for enterprise AI, but responsible access and security must scale with capability.</p>"),
make("sep10-anthropic-security","Anthropic Reports New Attempts to Misuse AI for Cyber Operations","Anthropic says its threat intelligence team has identified and disrupted operations where attackers attempted to use Claude for malicious activity.","Cybersecurity",["Cybersecurity","AI Agents","AI News","AI Tools","AI Research"],"Anthropic","https://www.anthropic.com/news","2026-09-10T10:00:00Z",IMG.security,"<h2>Security flash</h2><p>Anthropic's September threat-intelligence reporting describes attempts to misuse AI systems for malicious activity. The report highlights how capable models can become part of modern cyber workflows.</p><h2>Enterprise response</h2><p>AI deployments should use least-privilege access, strong monitoring, abuse detection and clear escalation paths.</p><h2>AI automation takeaway</h2><p>Agentic systems should be designed with constrained permissions and auditable actions from day one.</p>")
];
const cutoff=()=>new Date(Date.now()-72*60*60*1000).toISOString();
export default function News(){
 const [articles,setArticles]=useState<Article[]>(FRESH),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[cat,setCat]=useState("All"),[query,setQuery]=useState(""),[last,setLast]=useState(new Date()),[lang,setLang]=useState("en-US"),[gender,setGender]=useState("female"),[rate,setRate]=useState([1]),[voices,setVoices]=useState<SpeechSynthesisVoice[]>([]),[playing,setPlaying]=useState<string|null>(null),[paused,setPaused]=useState(false);
 const utter=useRef<SpeechSynthesisUtterance|null>(null);
 const load=async()=>{try{setRefreshing(true);const {data}=await supabase.from("news_articles").select("id,slug,title,summary,content,category,topics,source,source_url,source_published_at,image_url,image_alt,reading_minutes,author,published_at").gte("published_at",cutoff()).order("published_at",{ascending:false}).limit(40);const live=(data||[]) as Article[];const merged=[...live,...FRESH].filter((a,i,self)=>self.findIndex(x=>(x.source_url&&a.source_url&&x.source_url===a.source_url)||x.id===a.id)===i).sort((a,b)=>new Date(b.published_at).getTime()-new Date(a.published_at).getTime());setArticles(merged.slice(0,40));setLast(new Date());}catch{setArticles(FRESH)}finally{setLoading(false);setRefreshing(false)}};
 useEffect(()=>{load();const t=setInterval(load,60*60*1000);return()=>clearInterval(t)},[]);
 useEffect(()=>{const sync=()=>setVoices(window.speechSynthesis?.getVoices()||[]);sync();window.speechSynthesis?.addEventListener("voiceschanged",sync);return()=>window.speechSynthesis?.removeEventListener("voiceschanged",sync)},[]);
 const filtered=useMemo(()=>articles.filter(a=>(cat==="All"||a.category===cat||a.topics?.includes(cat))&&(`${a.title} ${a.summary} ${a.category} ${a.source||""}`).toLowerCase().includes(query.toLowerCase())),[articles,cat,query]);
 const voice=()=>{const ms=voices.filter(v=>v.lang?.toLowerCase().startsWith(lang.slice(0,2).toLowerCase()));if(!ms.length)return voices[0];const p=gender==="female"?/female|woman|samantha|zira|aria|jenny|google.*female|raveena/:/male|man|david|mark|alex|fred|google.*male/;return ms.find(v=>p.test(v.name.toLowerCase()))||ms[0]};
 const speak=(a:Article)=>{if(!window.speechSynthesis)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(strip(a.content||a.summary));u.lang=lang;u.rate=rate[0];const v=voice();if(v)u.voice=v;u.onend=()=>{setPlaying(null);setPaused(false)};utter.current=u;window.speechSynthesis.speak(u);setPlaying(a.id);setPaused(false)};
 const togglePause=()=>{if(!window.speechSynthesis)return;if(paused){window.speechSynthesis.resume();setPaused(false)}else{window.speechSynthesis.pause();setPaused(true)}};
 const stop=()=>{window.speechSynthesis.cancel();setPlaying(null);setPaused(false)};
 return <div className="min-h-screen bg-background"><Helmet><title>Live SEO & AI News | Crazy SEO Team</title><meta name="description" content="Latest SEO, AI, Google Search, AI Search, cybersecurity and technology news with source links and hourly updates."/><link rel="canonical" href="https://crazyseoteam.in/news"/></Helmet><Navbar/>
 <main className="pt-24 pb-16"><section className="container mx-auto px-4"><div className="rounded-3xl border bg-card/80 p-6 md:p-10 shadow-xl overflow-hidden relative"><div className="absolute inset-0 pointer-events-none bg-gradient-to-br from-primary/10 via-transparent to-primary/5"/><div className="relative"><div className="flex flex-wrap items-center gap-2 text-xs font-bold uppercase tracking-widest text-primary"><span className="inline-flex items-center gap-1"><Radio className="h-4 w-4"/> Live Newsroom</span><span className="rounded-full bg-red-500/10 px-3 py-1 text-red-600">LIVE FLASH</span></div><h1 className="mt-4 text-4xl md:text-6xl font-black tracking-tight">Latest SEO, AI & Technology News</h1><p className="mt-4 max-w-3xl text-muted-foreground text-base md:text-lg">Fresh September 2026 stories, source-linked reporting, SEO analysis and AI-search insights. Older stories are automatically removed from the live view.</p><div className="mt-6 flex flex-col lg:flex-row gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search latest news..." className="w-full rounded-xl border bg-background px-10 py-3 outline-none focus:ring-2 focus:ring-primary/30"/></div><Button onClick={load} variant="outline" disabled={refreshing}>{refreshing?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<RefreshCw className="mr-2 h-4 w-4"/>}Refresh</Button></div><div className="mt-3 text-xs text-muted-foreground">Updated {last.toLocaleTimeString()} · automatic refresh every hour · only fresh 72-hour stories shown</div></div></div>
 <div className="mt-6 flex gap-2 overflow-x-auto pb-2">{CATS.map(c=><button key={c} onClick={()=>setCat(c)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-semibold border transition ${cat===c?"bg-primary text-primary-foreground border-primary":"bg-card hover:bg-muted"}`}>{c}</button>)}</div>
 <div className="mt-5 rounded-2xl border bg-card p-4 flex flex-wrap items-center gap-3"><Volume2 className="h-5 w-5 text-primary"/><Select value={lang} onValueChange={setLang}><SelectTrigger className="w-[150px]"><SelectValue/></SelectTrigger><SelectContent>{LANGS.map(x=><SelectItem key={x.code} value={x.code}>{x.label}</SelectItem>)}</SelectContent></Select><Select value={gender} onValueChange={setGender}><SelectTrigger className="w-[130px]"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="female">Female voice</SelectItem><SelectItem value="male">Male voice</SelectItem></SelectContent></Select><div className="flex items-center gap-2"><span className="text-xs text-muted-foreground">Speed</span><Slider value={rate} onValueChange={setRate} min={0.7} max={1.5} step={0.1} className="w-28"/></div>{playing&&<><Button size="sm" variant="outline" onClick={togglePause}>{paused?<Play/>:<Pause/>}</Button><Button size="sm" variant="outline" onClick={stop}><Square/></Button></>}</div>
 {loading?<div className="py-20 flex justify-center"><Loader2 className="h-8 w-8 animate-spin text-primary"/></div>:<div className="mt-8 grid gap-7 md:grid-cols-2 lg:grid-cols-3">{filtered.map((a,i)=><article key={a.id} className={`group overflow-hidden rounded-2xl border bg-card shadow-sm hover:shadow-2xl transition-all duration-300 hover:-translate-y-1 ${i===0?"md:col-span-2 lg:col-span-2":""}`}><div className="relative aspect-[16/9] overflow-hidden bg-muted"><img src={imgFor(a)} alt={a.image_alt||a.title} loading={i<3?"eager":"lazy"} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"/><div className="absolute left-3 top-3 flex gap-2"><span className="rounded-full bg-background/90 px-3 py-1 text-xs font-bold text-primary">{a.category}</span>{i<3&&<span className="rounded-full bg-red-600 px-3 py-1 text-xs font-bold text-white">FLASH</span>}</div></div><div className="p-5"><div className="flex items-center justify-between gap-2 text-xs text-muted-foreground"><span>{a.source||"Crazy SEO Team"}</span><span className="inline-flex items-center gap-1"><Clock className="h-3.5 w-3.5"/>{a.reading_minutes||1} min</span></div><h2 className="mt-2 text-xl font-extrabold leading-tight group-hover:text-primary transition-colors">{a.title}</h2><p className="mt-2 text-sm text-muted-foreground line-clamp-3">{a.summary}</p><div className="mt-4 flex flex-wrap gap-2"><Button size="sm" onClick={()=>speak(a)}><Volume2 className="mr-2 h-4 w-4"/>Listen</Button>{a.source_url&&<a href={a.source_url} target="_blank" rel="noreferrer"><Button size="sm" variant="outline">Original source <ExternalLink className="ml-2 h-3.5 w-3.5"/></Button></a>}</div><div className="mt-3 text-xs text-muted-foreground">{new Date(a.published_at).toLocaleString()}</div></div></article>)}</div>}
 {!loading&&!filtered.length&&<div className="py-20 text-center text-muted-foreground"><Zap className="mx-auto h-8 w-8 mb-3 text-primary"/><p>No fresh story matches this filter yet.</p></div>}
 </section></main><Footer/><WhatsAppButton/></div>;
}
