import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowRight, Check, Copy, ImagePlus, MapPin, ShieldCheck, Sparkles, Trash2, Video } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { saveListing, saveMedia, type ClassifiedMedia } from "@/lib/classifiedStorage";

const cats=["Cars & Vehicles","Real Estate","Mobiles & Electronics","Jobs","Business & Industrial","Services","Furniture & Home","Fashion","Education","Agriculture","Animals & Pets","Construction","Other"];
const slugify=(s:string)=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"listing";

export default function PostAd(){
 const [step,setStep]=useState(1),[submitted,setSubmitted]=useState(false),[saving,setSaving]=useState(false),[liveUrl,setLiveUrl]=useState("");
 const [form,setForm]=useState({category:"",title:"",description:"",price:"",location:"",seller:"Individual",phone:""});
 const [photos,setPhotos]=useState<File[]>([]),[video,setVideo]=useState<File|null>(null);
 const set=(k:string,v:string)=>setForm(f=>({...f,[k]:v}));
 const photoUrls=useMemo(()=>photos.map(f=>URL.createObjectURL(f)),[photos]);
 const videoUrl=useMemo(()=>video?URL.createObjectURL(video):"",[video]);
 const addPhotos=(files:FileList|null)=>{if(!files)return;const incoming=Array.from(files).filter(f=>/^image\/(jpeg|png|webp|gif)$/.test(f.type)&&f.size<=5*1024*1024);setPhotos(p=>[...p,...incoming].slice(0,12));};
 const addVideo=(file:File|null)=>{if(!file)return;if(!/^video\/(mp4|webm|quicktime)$/.test(file.type)||file.size>50*1024*1024){alert("Please choose MP4, WebM or MOV video up to 50 MB.");return;}setVideo(file)};
 const publish=async()=>{if(!form.category||!form.title.trim()){alert("Please add category and title.");return}setSaving(true);try{const id=crypto.randomUUID();const media:ClassifiedMedia[]=photos.map((f,i)=>({id:`${id}-${i}`,kind:"photo",name:f.name,type:f.type,size:f.size}));const videoMeta=video?{id:`${id}-video`,kind:"video" as const,name:video.name,type:video.type,size:video.size}:undefined;await saveMedia(id,photos);if(video)await saveMedia(id,[video]);const listing={...form,id,title:form.title.trim(),photos:media,video:videoMeta,createdAt:new Date().toISOString()};saveListing(listing);const url=`${window.location.origin}/listing/${id}-${slugify(form.title)}`;setLiveUrl(url);setSubmitted(true)}finally{setSaving(false)}};
 if(submitted)return <div className="min-h-screen bg-slate-50 pt-36 pb-20"><div className="mx-auto max-w-xl px-4"><div className="rounded-3xl border bg-white p-8 text-center shadow-lg"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-emerald-50 text-emerald-600"><Check size={30}/></div><h1 className="mt-5 text-2xl font-black">Ad submitted successfully</h1><p className="mt-2 text-slate-500">Your live listing link has been generated.</p><div className="mt-5 flex gap-2"><Input readOnly value={liveUrl}/><Button onClick={()=>navigator.clipboard?.writeText(liveUrl)}><Copy size={16}/></Button></div><div className="mt-5 flex justify-center gap-3"><Button asChild className="rounded-xl"><Link to={liveUrl.replace(window.location.origin,"")}>Open Live Listing</Link></Button><Button variant="outline" asChild><Link to="/classifieds">Marketplace</Link></Button></div></div></div></div>;
 return <div className="min-h-screen bg-slate-50 pt-32 pb-20"><div className="mx-auto max-w-4xl px-4 lg:px-6"><Link to="/classifieds" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-blue-600"><ArrowLeft size={16}/> Back to Classifieds</Link><div className="mt-5 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm md:p-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><span className="text-xs font-bold uppercase tracking-[.2em] text-blue-600">Sell faster</span><h1 className="mt-1 text-3xl font-black">Post a New Ad</h1></div><div className="text-xs font-semibold text-slate-400">Step {step} of 3</div></div><div className="mt-6 grid grid-cols-3 gap-2">{["Basics","Details","Preview"].map((x,i)=><div key={x} className={`h-1.5 rounded-full ${i<step?'bg-blue-600':'bg-slate-100'}`}/>)}</div>
 {step===1&&<div className="mt-8 space-y-5"><label className="block text-sm font-semibold">Category<select value={form.category} onChange={e=>set('category',e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">Select category</option>{cats.map(c=><option key={c}>{c}</option>)}</select></label><label className="block text-sm font-semibold">Ad title<Input value={form.title} onChange={e=>set('title',e.target.value)} placeholder="Example: 2022 Maruti Swift VXi, excellent condition" className="mt-2 rounded-xl"/></label><label className="block text-sm font-semibold">Description<Textarea value={form.description} onChange={e=>set('description',e.target.value)} placeholder="Describe condition, features, age, documents and anything buyers should know..." className="mt-2 min-h-36 rounded-xl"/></label></div>}
 {step===2&&<div className="mt-8 grid gap-5 md:grid-cols-2"><label className="text-sm font-semibold">Price<Input value={form.price} onChange={e=>set('price',e.target.value)} placeholder="₹ Enter price" className="mt-2 rounded-xl"/></label><label className="text-sm font-semibold">Location<div className="relative mt-2"><MapPin className="absolute left-3 top-3 text-slate-400" size={17}/><Input value={form.location} onChange={e=>set('location',e.target.value)} placeholder="City, state, area" className="rounded-xl pl-9"/></div></label><label className="text-sm font-semibold">Seller type<select value={form.seller} onChange={e=>set('seller',e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3"><option>Individual</option><option>Business</option></select></label><label className="text-sm font-semibold">Contact number<Input value={form.phone} onChange={e=>set('phone',e.target.value)} placeholder="Phone / WhatsApp" className="mt-2 rounded-xl"/></label><div className="md:col-span-2 grid gap-3 sm:grid-cols-2"><label className="relative flex min-h-28 cursor-pointer flex-col items-center justify-center gap-2 rounded-2xl border-2 border-dashed border-slate-200 bg-slate-50 text-sm font-semibold text-slate-500 hover:border-blue-400"><ImagePlus size={22}/><span>Add photos</span><span className="text-xs font-normal">Up to 12 images · 5 MB each</span><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple className="absolute inset-0 cursor-pointer opacity-0" onChange={e=>addPhotos(e.target.files)}/></label><label className="relative flex min-h-28 cursor-pointer flex-col items-center justify-center gap-2 rounded-2xl border-2 border-dashed border-slate-200 bg-slate-50 text-sm font-semibold text-slate-500 hover:border-blue-400"><Video size={22}/><span>{video?video.name:"Add video"}</span><span className="text-xs font-normal">MP4/WebM/MOV · up to 50 MB</span><input type="file" accept="video/mp4,video/webm,video/quicktime" className="absolute inset-0 cursor-pointer opacity-0" onChange={e=>addVideo(e.target.files?.[0]||null)}/></label></div>{photos.length>0&&<div className="md:col-span-2 grid grid-cols-3 gap-3 sm:grid-cols-4">{photoUrls.map((src,i)=><div key={`${src}-${i}`} className="group relative aspect-square overflow-hidden rounded-xl border"><img src={src} alt={`Listing photo ${i+1}`} className="h-full w-full object-cover"/><button type="button" onClick={()=>setPhotos(p=>p.filter((_,n)=>n!==i))} className="absolute right-1 top-1 rounded-full bg-white/90 p-1 text-red-600 shadow"><Trash2 size={14}/></button></div>)}</div>}{videoUrl&&<div className="md:col-span-2 overflow-hidden rounded-xl border bg-black"><video src={videoUrl} controls className="max-h-72 w-full"/></div>}<div className="md:col-span-2 rounded-2xl bg-blue-50 p-4 text-sm text-blue-800"><ShieldCheck className="mb-1" size={18}/><b>Safety first:</b> Never share OTPs or payment credentials with buyers.</div></div>}
 {step===3&&<div className="mt-8 rounded-2xl border bg-slate-50 p-6"><div className="flex items-center gap-2 text-sm font-bold text-blue-700"><Sparkles size={17}/> Preview</div>{photoUrls[0]&&<img src={photoUrls[0]} alt={form.title} className="mt-4 aspect-video w-full rounded-2xl object-cover"/>}<h2 className="mt-4 text-2xl font-black">{form.title||"Your listing title"}</h2><p className="mt-1 text-lg font-bold">{form.price||"Price not set"}</p><p className="mt-2 text-sm text-slate-500">{form.location||"Location not set"} · {form.category||"Category not set"}</p><p className="mt-5 whitespace-pre-wrap text-slate-700">{form.description||"Your description will appear here."}</p>{video&&<p className="mt-4 text-sm font-semibold text-blue-700">✓ Video attached: {video.name}</p>}</div>}
 <div className="mt-8 flex justify-between gap-3 border-t pt-5">{step>1?<Button variant="outline" onClick={()=>setStep(step-1)} className="rounded-xl">Back</Button>:<span/>}{step<3?<Button onClick={()=>setStep(step+1)} disabled={step===1&&!form.category} className="rounded-xl">Continue <ArrowRight size={16}/></Button>:<Button onClick={publish} disabled={saving} className="rounded-xl bg-gradient-to-r from-blue-600 to-violet-600">{saving?"Publishing...":"Publish Ad"} <Check size={16}/></Button>}</div></div></div></div>;
}
