import { useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowRight, Check, ImagePlus, MapPin, ShieldCheck, Sparkles, Video } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

const cats = ["Cars & Vehicles","Real Estate","Mobiles & Electronics","Jobs","Business & Industrial","Services","Furniture & Home","Fashion","Education","Agriculture","Animals & Pets","Construction","Other"];

export default function PostAd(){
 const [step,setStep]=useState(1); const [submitted,setSubmitted]=useState(false);
 const [form,setForm]=useState({category:"",title:"",description:"",price:"",location:"",seller:"Individual",phone:""});
 const set=(k:string,v:string)=>setForm({...form,[k]:v});
 if(submitted) return <div className="min-h-screen bg-slate-50 pt-36 pb-20"><div className="mx-auto max-w-xl px-4"><div className="rounded-3xl border bg-white p-10 text-center shadow-lg"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-emerald-50 text-emerald-600"><Check size={30}/></div><h1 className="mt-5 text-2xl font-black">Ad submitted for review</h1><p className="mt-2 text-slate-500">Your listing is saved. Once approved, it will appear in the marketplace.</p><Button asChild className="mt-6 rounded-xl"><Link to="/classifieds">View Classifieds</Link></Button></div></div></div>;
 return <div className="min-h-screen bg-slate-50 pt-32 pb-20"><div className="mx-auto max-w-4xl px-4 lg:px-6"><Link to="/classifieds" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-blue-600"><ArrowLeft size={16}/> Back to Classifieds</Link><div className="mt-5 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm md:p-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><span className="text-xs font-bold uppercase tracking-[.2em] text-blue-600">Sell faster</span><h1 className="mt-1 text-3xl font-black">Post a New Ad</h1></div><div className="flex items-center gap-2 text-xs font-semibold text-slate-400">Step {step} of 3</div></div><div className="mt-6 grid grid-cols-3 gap-2">{["Basics","Details","Preview"].map((x,i)=><div key={x} className={`h-1.5 rounded-full ${i<step?'bg-blue-600':'bg-slate-100'}`}/>)}</div>
 {step===1&&<div className="mt-8 space-y-5"><label className="block text-sm font-semibold">Category<select value={form.category} onChange={e=>set('category',e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-blue-500"><option value="">Select category</option>{cats.map(c=><option key={c}>{c}</option>)}</select></label><label className="block text-sm font-semibold">Ad title<Input value={form.title} onChange={e=>set('title',e.target.value)} placeholder="Example: 2022 Maruti Swift VXi, excellent condition" className="mt-2 rounded-xl"/></label><label className="block text-sm font-semibold">Description<Textarea value={form.description} onChange={e=>set('description',e.target.value)} placeholder="Describe condition, features, age, documents and anything buyers should know..." className="mt-2 min-h-36 rounded-xl"/></label></div>}
 {step===2&&<div className="mt-8 grid gap-5 md:grid-cols-2"><label className="text-sm font-semibold">Price<Input value={form.price} onChange={e=>set('price',e.target.value)} placeholder="₹ Enter price" className="mt-2 rounded-xl"/></label><label className="text-sm font-semibold">Location<div className="relative mt-2"><MapPin className="absolute left-3 top-3 text-slate-400" size={17}/><Input value={form.location} onChange={e=>set('location',e.target.value)} placeholder="City, state, area" className="rounded-xl pl-9"/></div></label><label className="text-sm font-semibold">Seller type<select value={form.seller} onChange={e=>set('seller',e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3"><option>Individual</option><option>Business</option></select></label><label className="text-sm font-semibold">Contact number<Input value={form.phone} onChange={e=>set('phone',e.target.value)} placeholder="Phone / WhatsApp" className="mt-2 rounded-xl"/></label><div className="md:col-span-2 grid gap-3 sm:grid-cols-2"><div className="flex min-h-28 items-center justify-center gap-2 rounded-2xl border-2 border-dashed border-slate-200 bg-slate-50 text-sm font-semibold text-slate-500"><ImagePlus size={22}/> Add photos</div><div className="flex min-h-28 items-center justify-center gap-2 rounded-2xl border-2 border-dashed border-slate-200 bg-slate-50 text-sm font-semibold text-slate-500"><Video size={22}/> Add video</div></div><div className="md:col-span-2 rounded-2xl bg-blue-50 p-4 text-sm text-blue-800"><ShieldCheck className="mb-1" size={18}/><b>Safety first:</b> Never share OTPs or payment credentials with buyers. Verified sellers get a trust badge after verification.</div></div>}
 {step===3&&<div className="mt-8 rounded-2xl border bg-slate-50 p-6"><div className="flex items-center gap-2 text-sm font-bold text-blue-700"><Sparkles size={17}/> Preview</div><h2 className="mt-4 text-2xl font-black">{form.title||"Your listing title"}</h2><p className="mt-1 text-lg font-bold">{form.price||"Price not set"}</p><p className="mt-2 text-sm text-slate-500">{form.location||"Location not set"} · {form.category||"Category not set"}</p><p className="mt-5 whitespace-pre-wrap text-slate-700">{form.description||"Your description will appear here."}</p><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-xl bg-white p-4 text-sm"><b>Seller</b><div className="mt-1 text-slate-500">{form.seller}</div></div><div className="rounded-xl bg-white p-4 text-sm"><b>Contact</b><div className="mt-1 text-slate-500">{form.phone||"Not provided"}</div></div></div></div>}
 <div className="mt-8 flex justify-between gap-3 border-t pt-5">{step>1?<Button variant="outline" onClick={()=>setStep(step-1)} className="rounded-xl">Back</Button>:<span/>}{step<3?<Button onClick={()=>setStep(step+1)} disabled={step===1&&!form.category} className="rounded-xl">Continue <ArrowRight size={16}/></Button>:<Button onClick={()=>setSubmitted(true)} className="rounded-xl bg-gradient-to-r from-blue-600 to-violet-600">Submit Ad <Check size={16}/></Button>}</div>
 </div></div></div>;
}
