import {useEffect,useMemo,useState} from "react";
import {supabase} from "@/integrations/supabase/client";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Card,CardContent} from "@/components/ui/card";
import {MessageCircle,Send,Search,UserCircle2,Circle,ArrowLeft,Clock3} from "lucide-react";
import {toast} from "sonner";

type DirectoryUser={user_id:string;public_id:string;display_name:string|null;state:string|null;country:string|null;last_seen_at:string|null};
type Msg={id:string;sender_id:string;receiver_id:string;message:string;created_at:string;read_at:string|null};

const online=(last:string|null)=>!!last&&(Date.now()-new Date(last).getTime()<90000);
const lastSeen=(last:string|null)=>{if(!last)return "Never seen";const d=new Date(last);const sec=Math.max(0,Math.floor((Date.now()-d.getTime())/1000));if(sec<60)return "Active just now";if(sec<3600)return `Last seen ${Math.floor(sec/60)}m ago`;if(sec<86400)return `Last seen ${Math.floor(sec/3600)}h ago`;return `Last seen ${d.toLocaleString()}`};

export default function IdeasMessagesPanel({currentUserId}:{currentUserId:string|null}){
 const [people,setPeople]=useState<DirectoryUser[]>([]),[query,setQuery]=useState(""),[target,setTarget]=useState<DirectoryUser|null>(null),[messages,setMessages]=useState<Msg[]>([]),[text,setText]=useState(""),[loading,setLoading]=useState(false),[sending,setSending]=useState(false);

 const loadPeople=async(q:string)=>{if(!currentUserId)return;const {data,error}=await supabase.rpc("search_ideas_directory",{p_query:q.trim()});if(error){console.error(error);return}setPeople(((data||[]) as DirectoryUser[]).filter(x=>x.user_id!==currentUserId))};
 const touch=async()=>{if(!currentUserId)return;await supabase.from("idea_account_registry").update({last_seen_at:new Date().toISOString()}).eq("user_id",currentUserId)};
 const loadMessages=async(t:DirectoryUser)=>{if(!currentUserId)return;setLoading(true);const {data,error}=await supabase.from("idea_messages").select("id,sender_id,receiver_id,message,created_at,read_at").or(`and(sender_id.eq.${currentUserId},receiver_id.eq.${t.user_id}),and(sender_id.eq.${t.user_id},receiver_id.eq.${currentUserId})`).order("created_at",{ascending:true});if(error)toast.error(error.message);else setMessages((data||[]) as Msg[]);await supabase.from("idea_messages").update({read_at:new Date().toISOString()}).eq("receiver_id",currentUserId).eq("sender_id",t.user_id).is("read_at",null);setLoading(false)};
 useEffect(()=>{if(!currentUserId)return;loadPeople("");touch();const timer=window.setInterval(touch,30000);const channel=supabase.channel("ideas-messages-"+currentUserId).on("postgres_changes",{event:"INSERT",schema:"public",table:"idea_messages",filter:`receiver_id=eq.${currentUserId}`},payload=>{const m=payload.new as Msg;if(target?.user_id===m.sender_id){setMessages(v=>[...v,m]);void supabase.from("idea_messages").update({read_at:new Date().toISOString()}).eq("id",m.id)}}).subscribe();return()=>{window.clearInterval(timer);void supabase.removeChannel(channel)}},[currentUserId,target?.user_id]);
 useEffect(()=>{const t=window.setTimeout(()=>loadPeople(query),250);return()=>window.clearTimeout(t)},[query,currentUserId]);
 useEffect(()=>{if(target)loadMessages(target);else setMessages([])},[target?.user_id,currentUserId]);
 const send=async()=>{const value=text.trim();if(!currentUserId||!target||!value)return;if(value.length>5000)return toast.error("Message is limited to 5000 characters.");setSending(true);const {data,error}=await supabase.from("idea_messages").insert({sender_id:currentUserId,receiver_id:target.user_id,message:value}).select("id,sender_id,receiver_id,message,created_at,read_at").single();if(error)toast.error(error.message);else{setMessages(v=>[...v,data as Msg]);setText("");await supabase.from("idea_account_registry").update({last_seen_at:new Date().toISOString()}).eq("user_id",currentUserId)}setSending(false)};
 const timeline=useMemo(()=>messages.map(m=>({...m,time:new Date(m.created_at).toLocaleString()})),[messages]);
 if(!currentUserId)return <Card className="mt-4"><CardContent className="p-6 text-center"><MessageCircle className="mx-auto mb-2"/><p className="font-bold">Login required</p><p className="text-sm text-muted-foreground">Sign in to send and receive Ideas messages.</p></CardContent></Card>;
 return <div className="mt-4 grid gap-4 md:grid-cols-[300px_1fr]">
  <Card className={target?"hidden md:block":""}><CardContent className="p-4">
   <div className="mb-3 flex items-center gap-2"><MessageCircle className="text-primary"/><div><p className="font-bold">Messages</p><p className="text-xs text-muted-foreground">Direct chat by Ideas ID</p></div></div>
   <div className="relative"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input className="pl-9" placeholder="Search Public ID or name" value={query} onChange={e=>setQuery(e.target.value)}/></div>
   <div className="mt-3 space-y-2">{people.map(person=><button key={person.user_id} type="button" onClick={()=>setTarget(person)} className="w-full rounded-xl border p-3 text-left hover:bg-muted/60"><div className="flex items-center gap-3"><div className="relative size-10 rounded-full bg-muted flex items-center justify-center"><UserCircle2 className="size-8 text-muted-foreground"/><span className={`absolute bottom-0 right-0 size-3 rounded-full border-2 border-background ${online(person.last_seen_at)?"bg-green-500":"bg-muted-foreground"}`}/></div><div className="min-w-0 flex-1"><p className="truncate font-semibold">{person.display_name||"Ideas Member"}</p><p className="truncate text-xs text-muted-foreground">{person.public_id}</p><p className="text-[11px] text-muted-foreground">{online(person.last_seen_at)?"Online":lastSeen(person.last_seen_at)}</p></div></div></button>)}{!people.length&&<p className="py-8 text-center text-sm text-muted-foreground">No other Ideas ID found.</p>}</div>
  </CardContent></Card>
  <Card className={!target?"hidden md:block":""}><CardContent className="flex min-h-[520px] flex-col p-0">
   {target?<><div className="flex items-center gap-3 border-b p-4"><Button size="icon" variant="ghost" className="md:hidden" onClick={()=>setTarget(null)}><ArrowLeft className="size-4"/></Button><div className="relative size-11 rounded-full bg-muted flex items-center justify-center"><UserCircle2 className="size-9 text-muted-foreground"/><span className={`absolute bottom-0 right-0 size-3 rounded-full border-2 border-background ${online(target.last_seen_at)?"bg-green-500":"bg-muted-foreground"}`}/></div><div><p className="font-bold">{target.display_name||"Ideas Member"}</p><p className="text-xs text-muted-foreground">{target.public_id} • {online(target.last_seen_at)?"Online":lastSeen(target.last_seen_at)}</p></div></div>
   <div className="flex-1 space-y-3 overflow-y-auto p-4">{loading?<p className="py-10 text-center text-sm text-muted-foreground">Loading conversation...</p>:timeline.length?timeline.map(m=><div key={m.id} className={`flex ${m.sender_id===currentUserId?"justify-end":"justify-start"}`}><div className={`max-w-[82%] rounded-2xl px-4 py-2 ${m.sender_id===currentUserId?"bg-primary text-primary-foreground":"bg-muted"}`}><p className="whitespace-pre-wrap break-words text-sm">{m.message}</p><p className="mt-1 flex items-center gap-1 text-[10px] opacity-70"><Clock3 className="size-3"/>{m.time}</p></div></div>):<div className="flex h-full items-center justify-center text-center text-sm text-muted-foreground"><div><MessageCircle className="mx-auto mb-2"/><p>No messages yet.</p><p>Start the conversation with {target.display_name||"this member"}.</p></div></div>}</div>
   <div className="border-t p-3"><div className="flex gap-2"><Input value={text} maxLength={5000} placeholder="Write a message..." onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}}/><Button onClick={send} disabled={sending||!text.trim()}><Send className="mr-2 size-4"/>Send</Button></div><p className="mt-1 text-[11px] text-muted-foreground">Enter to send • 5000 character limit</p></div></>:<div className="flex flex-1 items-center justify-center p-8 text-center text-muted-foreground"><div><MessageCircle className="mx-auto mb-3 size-10"/><p className="font-bold text-foreground">Select an Ideas ID</p><p className="text-sm">Search a Public ID or name to start a private conversation.</p></div></div>}
  </CardContent></Card>
 </div>;
}
