import { Link } from "react-router-dom";
import { Search, FileText, Shield, Bot, Globe2, MessageSquareQuote, Tag, Code2, FileCode, Map, Eye, Users, CalendarDays, Link2, Cpu, ArrowRight, Sparkles } from "lucide-react";

type Tool = { title: string; desc: string; icon: typeof Search; action: { kind: "scroll"; to: string } | { kind: "route"; to: string }; badge?: string };
const TOOLS: Tool[] = [
  { title: "Keyword Research", desc: "Generate keyword seeds, intent ideas and topical targets.", icon: Search, action: { kind: "scroll", to: "public-tools-lab" }, badge: "Public" },
  { title: "AI Article Generator", desc: "Create SEO-ready content in the AI toolkit.", icon: FileText, action: { kind: "route", to: "/ai-tools" }, badge: "Public" },
  { title: "Website Audit", desc: "Run a real public-page technical and on-page check.", icon: Shield, action: { kind: "scroll", to: "public-tools-lab" }, badge: "Public" },
  { title: "LLM Checker", desc: "Check AI-readable entity, schema and content signals.", icon: Bot, action: { kind: "scroll", to: "public-tools-lab" }, badge: "Public" },
  { title: "GEO Checker", desc: "Generative Engine Optimization readiness score.", icon: Globe2, action: { kind: "scroll", to: "public-tools-lab" }, badge: "Public" },
  { title: "AEO Checker", desc: "Answer Engine Optimization readiness for direct answers and FAQs.", icon: MessageSquareQuote, action: { kind: "scroll", to: "public-tools-lab" }, badge: "Public" },
  { title: "Meta Generator", desc: "Generate title and meta description starter markup.", icon: Tag, action: { kind: "scroll", to: "public-tools-lab" }, badge: "Public" },
  { title: "Schema Generator", desc: "Generate Organization JSON-LD ready to customize.", icon: Code2, action: { kind: "scroll", to: "public-tools-lab" }, badge: "Public" },
  { title: "Robots.txt Generator", desc: "Create a safe robots.txt starter with sitemap reference.", icon: FileCode, action: { kind: "scroll", to: "public-tools-lab" }, badge: "Public" },
  { title: "Sitemap Generator", desc: "Generate a clean XML sitemap starter.", icon: Map, action: { kind: "scroll", to: "public-tools-lab" }, badge: "Public" },
  { title: "SERP Preview", desc: "Preview title, URL and description as a search result.", icon: Eye, action: { kind: "scroll", to: "public-tools-lab" }, badge: "Public" },
  { title: "Competitor Analysis", desc: "Public-page benchmarking starter without login.", icon: Users, action: { kind: "scroll", to: "public-tools-lab" }, badge: "Public" },
  { title: "Content Planner", desc: "Generate topic and intent seeds for a content plan.", icon: CalendarDays, action: { kind: "scroll", to: "public-tools-lab" }, badge: "Public" },
  { title: "Internal Link Generator", desc: "Review a public URL and plan contextual internal links.", icon: Link2, action: { kind: "scroll", to: "public-tools-lab" }, badge: "Public" },
  { title: "NLP Analyzer", desc: "Extract visible entities and topical signals from a public page.", icon: Cpu, action: { kind: "scroll", to: "public-tools-lab" }, badge: "Public" },
];
export default function SEOToolsGrid() {
  return <section className="relative py-20 px-4 overflow-hidden"><div className="absolute inset-0 pointer-events-none opacity-40" style={{ background: "radial-gradient(600px circle at 20% 10%, hsl(230 90% 50% / 0.25), transparent 60%), radial-gradient(500px circle at 80% 80%, hsl(280 90% 60% / 0.22), transparent 60%)" }}/><div className="container mx-auto max-w-7xl relative"><div className="text-center mb-14"><span className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-cyan-200 bg-cyan-50 text-xs font-semibold text-cyan-700 mb-4"><Sparkles size={14}/> Free Public SEO Toolkit</span><h2 className="text-4xl md:text-5xl font-black text-slate-900 mb-4 tracking-tight">SEO + AEO + GEO Tools — <span className="bg-gradient-to-r from-cyan-400 via-blue-500 to-purple-500 bg-clip-text text-transparent">Free & Public</span></h2><p className="text-lg text-slate-600 max-w-3xl mx-auto">Run public tools without an account. Real URL checks use publicly accessible page signals; generators can be exported as files.</p></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">{TOOLS.map(tool=>{const Icon=tool.icon;const inner=<div className="group relative h-full glass-card glass-sheen p-6"><div className="absolute inset-0 rounded-2xl opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none" style={{background:"linear-gradient(135deg,hsl(230 90% 50% / .08),hsl(280 90% 60% / .08))"}}/><div className="relative"><div className="flex items-start justify-between mb-4"><div className="w-12 h-12 rounded-xl bg-gradient-to-br from-blue-600 to-purple-600 flex items-center justify-center shadow-[0_8px_30px_-8px_hsl(230_90%_60%/0.7)]"><Icon size={22} className="text-white"/></div><span className="text-[10px] font-bold px-2 py-1 rounded-full bg-emerald-500/10 border border-emerald-400/30 text-emerald-700 uppercase tracking-wider">{tool.badge}</span></div><h3 className="text-lg font-bold text-slate-900 mb-2">{tool.title}</h3><p className="text-sm text-slate-600 mb-5 leading-relaxed">{tool.desc}</p><div className="flex items-center gap-2 text-sm font-semibold text-blue-600 group-hover:text-violet-600">Open Tool <ArrowRight size={16} className="group-hover:translate-x-1 transition-transform"/></div></div></div>;return tool.action.kind==="route"?<Link key={tool.title} to={tool.action.to}>{inner}</Link>:<a key={tool.title} href={`#${tool.action.to}`} className="text-left h-full">{inner}</a>})}</div></div></section>;
}
