-- Ideas community social layer
create table if not exists public.idea_profiles (user_id uuid primary key references auth.users(id) on delete cascade, display_name text not null, bio text, avatar_url text, cover_url text, location text, website_url text, linkedin_url text, github_url text, instagram_url text, twitter_url text, updated_at timestamptz not null default now());
create table if not exists public.idea_follows (follower_id uuid not null references auth.users(id) on delete cascade, following_id uuid not null references auth.users(id) on delete cascade, created_at timestamptz not null default now(), primary key (follower_id,following_id), check(follower_id<>following_id));
create table if not exists public.idea_friendships (requester_id uuid not null references auth.users(id) on delete cascade, addressee_id uuid not null references auth.users(id) on delete cascade, status text not null default 'pending' check(status in ('pending','accepted','rejected','blocked')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), primary key(requester_id,addressee_id), check(requester_id<>addressee_id));
alter table public.idea_posts add column if not exists visibility text not null default 'public' check(visibility in ('public','friends'));
alter table public.idea_posts add column if not exists post_type text not null default 'post' check(post_type in ('post','question'));
alter table public.idea_posts add column if not exists updated_at timestamptz not null default now();
create index if not exists idea_posts_user_created_idx on public.idea_posts(user_id,created_at desc);
create index if not exists idea_posts_visibility_idx on public.idea_posts(visibility,status,created_at desc);
create index if not exists idea_follows_following_idx on public.idea_follows(following_id);
create index if not exists idea_friendships_addressee_idx on public.idea_friendships(addressee_id,status);
alter table public.idea_profiles enable row level security;
alter table public.idea_follows enable row level security;
alter table public.idea_friendships enable row level security;
drop policy if exists "Idea profiles are public" on public.idea_profiles;
create policy "Idea profiles are public" on public.idea_profiles for select to anon,authenticated using(true);
drop policy if exists "Users manage own idea profile" on public.idea_profiles;
create policy "Users manage own idea profile" on public.idea_profiles for insert to authenticated with check((select auth.uid())=user_id);
create policy "Users update own idea profile" on public.idea_profiles for update to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
drop policy if exists "Users can read follows" on public.idea_follows;
create policy "Users can read follows" on public.idea_follows for select to authenticated using((select auth.uid())=follower_id or (select auth.uid())=following_id);
create policy "Users can follow" on public.idea_follows for insert to authenticated with check((select auth.uid())=follower_id);
create policy "Users can unfollow" on public.idea_follows for delete to authenticated using((select auth.uid())=follower_id);
drop policy if exists "Users can read friendships" on public.idea_friendships;
create policy "Users can read friendships" on public.idea_friendships for select to authenticated using((select auth.uid())=requester_id or (select auth.uid())=addressee_id);
create policy "Users can send friend requests" on public.idea_friendships for insert to authenticated with check((select auth.uid())=requester_id);
create policy "Users can respond to friend requests" on public.idea_friendships for update to authenticated using((select auth.uid())=addressee_id) with check((select auth.uid())=addressee_id);
create policy "Users can remove friendship" on public.idea_friendships for delete to authenticated using((select auth.uid())=requester_id or (select auth.uid())=addressee_id);
drop policy if exists "Anyone can read approved ideas" on public.idea_posts;
drop policy if exists "Community can read approved ideas by visibility" on public.idea_posts;
create policy "Community can read approved ideas by visibility" on public.idea_posts for select to anon,authenticated using(status='approved' and (visibility='public' or user_id=(select auth.uid()) or (visibility='friends' and (select auth.uid()) is not null and exists(select 1 from public.idea_friendships f where f.status='accepted' and ((f.requester_id=public.idea_posts.user_id and f.addressee_id=(select auth.uid())) or (f.addressee_id=public.idea_posts.user_id and f.requester_id=(select auth.uid())))))));
drop policy if exists "Users can create ideas" on public.idea_posts;
create policy "Users can create ideas" on public.idea_posts for insert to authenticated with check((select auth.uid())=user_id and status='pending' and visibility in ('public','friends') and post_type in ('post','question'));
