// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

// Attendance/CRM must always use the connected Crazy SEO Team Supabase project.
// This prevents an incorrect Vercel env value from routing production to a
// different Supabase project whose schema does not contain crm_attendance.
const SUPABASE_URL = 'https://pbkyoszlgyhpygofemij.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_vEsFObkUZcIiVdxMoPo-7A_mFevsgwq';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
