import { useState } from "react";
import { BarChart3, CheckCircle2, Flag, LayoutList, MoreHorizontal, Search, ShieldCheck, Store, Users } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

const rows=[
 {title:"2022 Maruti Suzuki Swift VXi",seller:"Amit Kumar",location:"Muzaffarpur, Bihar",status:"Active",price:"₹5.25 Lakh"},
 {title:"2 BHK Ready to Move Flat",seller:"Bihar Homes",location:"Muzaffarpur, Bihar",status:"Featured",price:"₹32 Lakh"},
 {title:"iPhone 15 128GB",seller:"Rahul Verma",location:"Patna, Bihar",status:"Pending",price:"₹48,000"},
 {title:"Digital Marketing Executive",seller:"Growth Studio",location:"Remote / Bihar",status:"Active",price:"₹25,000/mo"},
];
export default function ClassifiedAdmin(){const [q,setQ]=useState(""); const [tab,setTab]=useState("Listings"); const filtered=rows.filter(r=>`${r.title} ${r.seller} ${r.location}`.toLowerCase().includes(q.toLowerCase())); return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-600">Marketplace control center</p><h1 className="text-3xl font-black">Classifieds Admin</h1><p className="mt-1 text-sm text-slate-500">Manage listings, sellers, businesses, reports and monetization.</p></div><Button className="rounded-xl"><ShieldCheck size={16}/> Review queue</Button></div><div className="grid gap-4 md:grid-cols-4">{[["Listings","12,480",LayoutList],["Users","8,920",Users],["Businesses","1,240",Store],["Reports","28",Flag]].map(([a,b,I])=><div key={a as string} className="rounded-2xl border bg-white p-5"><I className="text-blue-600" size={19}/><p className="mt-3 text-sm text-slate-500">{a as string}</p><p className="text-2xl font-black">{b as string}</p></div>)}</div><div className="rounded-2xl border bg-white shadow-sm"><div className="flex flex-wrap gap-2 border-b p-3">{["Listings","Sellers","Businesses","Categories","Reports","Payments","Coupons"].map(x=><button key={x} onClick={()=>setTab(x)} className={`rounded-lg px-3 py-2 text-sm font-semibold ${tab===x?'bg-blue-50 text-blue-700':'text-slate-500 hover:bg-slate-50'}`}>{x}</button>)}</div><div className="p-4"><div className="relative max-w-md"><Search className="absolute left-3 top-2.5 text-slate-400" size={17}/><Input value={q} onChange={e=>setQ(e.target.value)} placeholder={`Search ${tab.toLowerCase()}...`} className="rounded-xl pl-9"/></div>{tab==="Listings"?<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b text-xs uppercase tracking-wider text-slate-400"><tr><th className="pb-3">Listing</th><th>Seller</th><th>Location</th><th>Price</th><th>Status</th><th/></tr></thead><tbody className="divide-y">{filtered.map(r=><tr key={r.title}><td className="py-4 font-semibold">{r.title}</td><td className="py-4 text-slate-600">{r.seller}</td><td className="py-4 text-slate-500">{r.location}</td><td className="py-4 font-bold">{r.price}</td><td className="py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${r.status==='Active'?'bg-emerald-50 text-emerald-700':r.status==='Pending'?'bg-amber-50 text-amber-700':'bg-blue-50 text-blue-700'}`}>{r.status}</span></td><td><MoreHorizontal size={17} className="text-slate-400"/></td></tr>)}</tbody></table></div>:<div className="mt-8 rounded-xl bg-slate-50 p-10 text-center"><BarChart3 className="mx-auto text-slate-300"/><h3 className="mt-3 font-bold">{tab} management</h3><p className="mt-1 text-sm text-slate-500">The control surface is ready for your Supabase marketplace data.</p></div>}</div></div></div>}
