import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import { Check, X, Trash2, ExternalLink, Search, RefreshCw, Loader2, UserRound, Users, Megaphone } from "lucide-react";

type Listing = { id:string; title:string; description:string; category:string; city?:string; state?:string; seller_name?:string; seller_email?:string; seller_phone?:string; status:string; created_at:string; is_verified?:boolean };
type Account = { id:string; public_id:string; name:string; email:string; phone?:string; profile_photo_url?:string; status:string; created_at:string; last_seen_at?:string };

const statuses = ["all","pending","active","rejected"];

export default function ClassifiedModeration(){
  const [rows,setRows]=useState<Listing[]>([]); const [accounts,setAccounts]=useState<Account[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const [q,setQ]=useState(""); const [status,setStatus]=useState("pending"); const [accountQ,setAccountQ]=useState("");
  const load=async()=>{setLoading(true); const db=supabase as any; const [listingsResult,accountsResult]=await Promise.all([db.from("classified_listings").select("*").order("created_at",{ascending:false}),db.from("classified_account_registry").select("id,public_id,name,email,phone,profile_photo_url,status,created_at,last_seen_at").order("created_at",{ascending:false})]); if(listingsResult.error){toast.error("Could not load classifieds",{description:listingsResult.error.message});setRows([])}else setRows(listingsResult.data||[]); if(accountsResult.error){toast.error("Could not load Marketplace users",{description:accountsResult.error.message});setAccounts([])}else setAccounts(accountsResult.data||[]); setLoading(false)};
  useEffect(()=>{load()},[]);
  const act=async(id:string,next:string)=>{setBusy(id); const {error}=await (supabase as any).from("classified_listings").update({status:next,updated_at:new Date().toISOString()}).eq("id",id); if(error) toast.error(`${next} failed`,{description:error.message}); else {toast.success(next==="active"?"Listing accepted and published":next==="rejected"?"Listing rejected":"Listing deleted"); await load()} setBusy(null)};
  const remove=async(id:string)=>{if(!confirm("Permanently delete this listing and its media?"))return;setBusy(id);const {error}=await (supabase as any).from("classified_listings").delete().eq("id",id);if(error)toast.error("Delete failed",{description:error.message});else{toast.success("Listing permanently deleted");await load()}setBusy(null)};
  const filtered=useMemo(()=>rows.filter(r=>(status==="all"||r.status===status)&&(!q.trim()||`${r.title} ${r.description} ${r.seller_name} ${r.city} ${r.state}`.toLowerCase().includes(q.toLowerCase()))),[rows,status,q]); const filteredAccounts=useMemo(()=>accounts.filter(a=>!accountQ.trim()||`${a.public_id} ${a.name} ${a.email} ${a.phone}`.toLowerCase().includes(accountQ.toLowerCase())),[accounts,accountQ]); const accountAction=async(id:string,next:"approved"|"pending")=>{setBusy(id);const {error}=await (supabase as any).from("classified_account_registry").update({status:next,last_seen_at:new Date().toISOString()}).eq("id",id);if(error)toast.error("Account update failed",{description:error.message});else{toast.success(next==="approved"?"Account approved":"Account moved to pending");await load()}setBusy(null)}; const deleteAccount=async(a:Account)=>{if(!confirm(`Permanently delete Marketplace account ${a.public_id} (${a.email})?`))return;setBusy(a.id);const {error}=await (supabase as any).from("classified_account_registry").delete().eq("id",a.id);if(error)toast.error("Account delete failed",{description:error.message});else{toast.success("Marketplace account deleted");await load()}setBusy(null)};
  const count=(s:string)=>rows.filter(r=>r.status===s).length;
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-black">Classified Moderation</h1><p className="text-sm text-muted-foreground">Review every listing before it appears publicly.</p></div><Button variant="outline" className="rounded-2xl" onClick={load}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button></div>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-6"><div className="rounded-2xl border bg-card p-4"><div className="flex items-center gap-2 text-xs text-muted-foreground"><Users className="h-4 w-4"/>Marketplace Users</div><div className="mt-1 text-2xl font-black">{accounts.length}</div></div>{[["pending","Pending"],["active","Published"],["rejected","Rejected"],["all","All Posts"]].map(([s,label])=><button key={s} onClick={()=>setStatus(s)} className={`rounded-2xl border p-4 text-left transition ${status===s?"border-primary bg-primary/5":"bg-card"}`}><div className="text-xs text-muted-foreground">{label}</div><div className="mt-1 text-2xl font-black">{s==="all"?rows.length:count(s)}</div></button>)}<div className="rounded-2xl border bg-card p-4"><div className="flex items-center gap-2 text-xs text-muted-foreground"><Megaphone className="h-4 w-4"/>Total Ads</div><div className="mt-1 text-2xl font-black">{rows.length}</div></div></div>
    <div className="rounded-2xl border bg-muted/30 p-4 space-y-4"><div><div className="text-sm font-semibold">Marketplace user accounts: {accounts.length}</div><div className="mt-1 text-xs text-muted-foreground">Full account details, approval status and permanent delete controls.</div></div><div className="relative max-w-lg"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9 rounded-2xl" placeholder="Search user, Gmail, phone or CST ID..." value={accountQ} onChange={e=>setAccountQ(e.target.value)}/></div><div className="space-y-3">{filteredAccounts.map(a=><div key={a.id} className="rounded-2xl border bg-card p-4"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex min-w-0 items-start gap-3">{a.profile_photo_url?<img src={a.profile_photo_url} className="h-12 w-12 rounded-full object-cover" alt={a.name}/>:<div className="flex h-12 w-12 items-center justify-center rounded-full bg-muted"><UserRound className="h-5 w-5"/></div>}<div><div className="flex flex-wrap items-center gap-2"><p className="font-bold">{a.name}</p><Badge variant={a.status==="approved"?"default":"outline"}>{a.status}</Badge><Badge variant="secondary">{a.public_id}</Badge></div><div className="mt-1 grid gap-1 text-sm text-muted-foreground md:grid-cols-2"><span>📧 {a.email}</span><span>📞 {a.phone||"No phone"}</span><span>🗓 Created: {new Date(a.created_at).toLocaleString()}</span><span>👁 Last seen: {a.last_seen_at?new Date(a.last_seen_at).toLocaleString():"Never"}</span></div></div></div><div className="flex flex-wrap gap-2">{a.status!=="approved"&&<Button size="sm" onClick={()=>accountAction(a.id,"approved")} disabled={busy===a.id}><Check className="mr-1 h-4 w-4"/>Approve</Button>}{a.status==="approved"&&<Button size="sm" variant="outline" onClick={()=>accountAction(a.id,"pending")} disabled={busy===a.id}><X className="mr-1 h-4 w-4"/>Unapprove</Button>}<Button size="sm" variant="outline" className="text-destructive" onClick={()=>deleteAccount(a)} disabled={busy===a.id}><Trash2 className="mr-1 h-4 w-4"/>Delete Account</Button></div></div></div>)}{filteredAccounts.length===0&&<div className="rounded-2xl border p-8 text-center text-muted-foreground">No Marketplace accounts found.</div>}</div></div>
    <div className="relative max-w-lg"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9 rounded-2xl" placeholder="Search title, seller, city..." value={q} onChange={e=>setQ(e.target.value)}/></div>
    {loading?<div className="flex justify-center py-16"><Loader2 className="animate-spin"/></div>:<div className="space-y-3">{filtered.map(r=><div key={r.id} className="rounded-3xl border bg-card/80 p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold text-lg">{r.title}</h2><Badge variant={r.status==="active"?"default":"outline"}>{r.status}</Badge></div><p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{r.description}</p><div className="mt-4 flex flex-wrap items-center gap-4 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1"><UserRound className="h-3.5 w-3.5"/>{r.seller_name||"Marketplace Member"}</span><span>{r.seller_email||"No email"}</span><span>{r.city||"India"}{r.state?`, ${r.state}`:""}</span><span>{new Date(r.created_at).toLocaleString()}</span></div></div><div className="flex flex-wrap gap-2">{r.status!=="active"&&<Button size="sm" className="rounded-xl" disabled={busy===r.id} onClick={()=>act(r.id,"active")}><Check className="mr-1 h-4 w-4"/>Accept</Button>}{r.status!=="rejected"&&<Button size="sm" variant="outline" className="rounded-xl" disabled={busy===r.id} onClick={()=>act(r.id,"rejected")}><X className="mr-1 h-4 w-4"/>Reject</Button>}<Button size="sm" variant="outline" className="rounded-xl text-destructive" disabled={busy===r.id} onClick={()=>remove(r.id)}><Trash2 className="mr-1 h-4 w-4"/>Delete</Button><Button size="sm" variant="ghost" className="rounded-xl" asChild><a href={`/listing/${r.id}`} target="_blank" rel="noreferrer"><ExternalLink className="h-4 w-4"/></a></Button></div></div></div>)}{filtered.length===0&&<div className="rounded-3xl border p-12 text-center text-muted-foreground">No listings in this queue.</div>}</div>}
  </div>
}
